### ISSUE TITLE
Exclusions not working?

### ISSUE THREAD

**Issue by dopplershift** [actions/upload-artifact#100]
**Describe the bug**
Excluding files doesn't seem to work for me. I have the following config:

```yml
    - name: Upload docs as artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.python-version }}-docs
        path: |
          docs/build/html
          !docs/_static/*.pdf
```
and I find e.g. `docs/_static/NWS_10-201.pdf` in my uploaded artifact.

**Version**
- [ ] V1
- [x] V2

**Environment**
- [ ] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

**Run/Repo Url**
https://github.com/Unidata/MetPy/actions
