### ISSUE TITLE
Artifact upload from a different job overwrites the old artifact

### ISSUE THREAD

**Issue by aminya** [actions/upload-artifact#115]
**Describe the bug**
Artifact upload from a different job overwrites the old artifact. In 2.0.1 I could upload artifacts, and they ended up in the same artifact, but recently the last upload overwrites the artifacts!

**Version**
- [ ] V1
- [x] V2

**Environment**
- [ ] self-hosted
- [x] Linux
- [x] Windows
- [x] Mac

**Screenshots**

**Run/Repo Url**
https://github.com/JuliaPlots/Plots.jl/actions/runs/212117396

**How to reproduce**
```yaml
name: Test

on: push

defaults:
  run:
    shell: bash

jobs:
  Upload:
    runs-on: ubuntu-latest
    matrix:
			filename:
				- file1
				- file2
    steps:
      - uses: actions/checkout@v2
	  - run: |
		     echo hey >> testfolder/{{matrix.filename}}.txt
      - name: Upload all
        uses: actions/upload-artifact@v2-preview
        with:
          path: ./

  Create_PR:
    needs: Upload
    runs-on: ubuntu-latest
    steps:
      - name: Download all
        uses: actions/download-artifact@v2
      - name: Move the content of the directory to the root
        run: |
          rsync -a artifact/* ./
          rm -d -r artifact
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: UploadTest
          title: "[AUTO] upload test"
          labels: UploadTest
          branch: "UploadTest"
```

**Additional context**

In the previous versions, it was not like this.

**Comment by yacaovsnc** [comment]
The behavior of artifacts have not changed recently except we fixed a bug where we displayed incorrect size on UI. (#98)

Artifacts act like folders, and is open for modification during the entire duration of the run so jobs in the same run can add and modify/replace files in this artifact. 

Is this not what you have observed?  Do you have an example of the bug?

**Comment by konradpabjan** [comment]
When uploading to the same artifact via multiple jobs you have to be careful as things can be overwritten. Some more information: https://github.com/actions/upload-artifact#uploading-to-the-same-artifact

I tried following your example YAML but I could not reproduce an error. In the linked run that you provided, I noticed that there are multiple different types of operating systems and versions in your matrix. It is possible that, different operating systems are overwriting files with the same name that were uploaded. I would double check that.

Here is an example that I quickly put together that you can use for verification:

```
name: Test_Artifact_V2
on: [push]
jobs:
  Upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        filename: [file1,file2]
    steps:
    - run: |
        mkdir testfolder
        echo hey >> testfolder/${{matrix.filename}}.txt
    - name: Upload all
      uses: actions/upload-artifact@v2
      with:
        path: ./

  Verify_Artifact:
    needs: Upload
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt install tree
      - name: Download all
        uses: actions/download-artifact@v2
      - name: Display contents of artifact
        run: |
          tree .

```

https://github.com/konradpabjan/artifact-test/runs/1135976285?check_suite_focus=true
