### ISSUE TITLE
Preserve Upload Location?

### ISSUE THREAD

**Issue by kwhat** [actions/upload-artifact#119]
**Describe the bug**

**Version**
- [ ] V1
- [X] V2

**Environment**
- [ ] self-hosted
- [X] Linux
- [X] Windows
- [X] Mac

**Run/Repo Url**
https://github.com/kwhat/jnativehook/blob/maven/.github/workflows/package.yml

**How to reproduce**
Use upload-artifact to upload the entire project:
```
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: nightly-build
          path: ${{github.workspace}}/**/*
          if-no-files-found: error
```

Generate a new file:
```
      - name: Generate
        shell: bash
        run: |
          mkdir ${{github.workspace}}/src/main/resources/test
          echo "TEST" > ${{github.workspace}}/src/main/resources/test/file.txt
```

Then use upload-artifact to upload a pattern:
```
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: nightly-build
          path: ${{github.workspace}}/src/main/resources/**/*
          if-no-files-found: error
```

**Additional context**
I was expecting the contents of the resources folder to be at `src/main/resources/` in the nightly-build artifact.  Sadly it put everything matched by `**/*` in `/` in the artifact.  Is there a way to control the artifact location? Should I just be re-uploading everything?  Creating lots of different artifacts?
