### ISSUE TITLE
Use environment variable in file names

### ISSUE THREAD

**Issue by NPellet** [actions/upload-artifact#120]
**Describe the bug**
Actually it's maybe more of a feature request. It would be very convenient if environment variables could be used to set the path of the artifacts

**Version**
- [ ] V1
- [x] V2

**Environment**
- [ ] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

**How to reproduce**
Consider the following (non reproducible) action exemple:

```
    - run: echo "::set-env name=MY_VAR::6"
    - name: Save artifact
      uses: actions/upload-artifact@v2
      with:
        name: Artifact_${MY_VAR}
        path: /path/to/file_${MY_VAR}.extension
```
