### ISSUE TITLE
Upload-artifact not working for steps running in containers

### ISSUE THREAD

**Issue by zakkak** [actions/upload-artifact#13]
Hello, 

I have a yml using a container to run steps:
```
    runs-on: ubuntu-18.04
    container:
      image: my-container-on-docker-hub:latest
      volumes:
        - /github/home/.folder:/github/home/.folder
    steps:
    - name: ls
      run: ls -la $HOME
    - uses: actions/upload-artifact@master
      with:
        name: my-artifact
        path: /github/home/.folder
```

Inside the container if I `ls -la /github/home` I get:
```
total 16
drwxr-xr-x 4 1001  115 4096 Sep 12 23:47 .
drwxr-xr-x 4 root root 4096 Sep 12 23:47 ..
drwxr-xr-x 3 root root 4096 Sep 12 23:47 .folder
drwxr-xr-x 2 root root 4096 Sep 12 23:47 .ssh
```

However the `upload-artifact` step returns:
```
Run actions/upload-artifact@master
  with:
    name: my-artifact
    path: /github/home/.folder
##[error]Path does not exist /github/home/.folder
##[error]Exit code 1 returned from process: file name '/home/runner/runners/2.157.3/bin/Runner.PluginHost', arguments 'action "GitHub.Runner.Plugins.Artifact.PublishArtifact, Runner.Plugins"'.
```

I suspect that `upload-artifact` runs outside of the container and that's why I tried using `volumes` to make the data accessible on both sides, but it didn't help.
Is this an issue with `volumes` or `upload-artifact`?

Thanks
