### ISSUE TITLE
Support symbolic link in path

### ISSUE THREAD

**Issue by freak4pc** [actions/upload-artifact#134]
**Describe the bug**
If `path` to a file involves a symbolic link, the file is not found

**Version**
- [ ] V1
- [x] V2

**Environment**
- [ ] self-hosted
- [ ] Linux
- [x] Windows
- [ ] Mac

**How to reproduce**

Running as 

```yml
- name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Store executable
        path: .build
```

Works, and the big zip file looks as follows:

<img width="646" alt="image" src="https://user-images.githubusercontent.com/605076/94992133-89303700-0590-11eb-9d5e-96ea37c0a0da.png">

When trying this, though:
```yml
- name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Store executable
        path: .build/release/prism.exe
```

It fail, since `release` is actually a symlink to to `x86_64-unknown-windows-msvc/release`. 

Using `.build/x86_64-unknown-windows-msvc/release/prism.exe` directly does work. 

Notice also that the downloaded ZIP contains a double copy of this since the symlink is resolved as a regular uploaded file and not counted as a symbolic link (This seems to be related to #93)
