### ISSUE TITLE
Store artifacts step taking forever

### ISSUE THREAD

**Issue by KjellMorgenstern** [actions/upload-artifact#163]
**Describe the bug**
Storing a directory as artifact on a MacOS Catalina runner took forever (canceled after 32 minutes, after 12 minutes on a second run)
This seems to happen each time.
A 'du' command before the store artifact step shows that the uncompressed size of the folder that should be stored is about 504MB.
When the folder is archived to a tar.gz, the file was stored without a problem. 

**Version**
- [ ] V1
- [x] V2

**Environment**
- [ ] self-hosted
- [ ] Linux
- [ ] Windows
- [x] Mac

**Additional context**
I had a folder archived:

```
- name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: MyAppCatalina-b${{ github.run_number }}
          path: deploy-app
          retention-days: 1
```

Expected: Don't stall on directories / log progress messages / timeout / predict and log artifact size
