### ISSUE TITLE
support env var in name or path

### ISSUE THREAD

**Issue by FernandoMiguel** [actions/upload-artifact#17]
```
    - name: publish
      uses: actions/upload-artifact@master
      with:
        name: mypackage-$GITHUB_SHA
        path: ./OUT/mypackage-$GITHUB_SHA
```

**Comment by 1138-4EB** [comment]
I think that you can achieve it with `${{ github.sha }}`.

**Comment by FernandoMiguel** [comment]
@1138-4EB thank, will give it a try

**Comment by ztl8702** [comment]
What about environment variables like `HOME`?
```
    - name: publish
      uses: actions/upload-artifact@master
      with:
        name: mypackage
        path: ${HOME}/output
```

^ this didn't work, `${HOME}` was interpreted verbatim
