### ISSUE TITLE
Ability to delete local artifact after upload/download

### ISSUE THREAD

**Issue by dentuzhik** [actions/upload-artifact#170]
**Describe the issue**
This is rather a feature request.

We are using `@actions/upload-artifact` and `@actions/download-artifact` with workflows which run on self-hosted runners to build and deploy mobile applications. 

Because of the way how our workflows and jobs are compositioned, `build` and `upload` jobs are separated from each other. E.g. matrixed "build jobs" run Xcode / Android Studio to produce actual deployable artifacts for different environments and upload artifacts to Github, and "upload jobs" download artifacts later on and upload them to thirdparties (App Store, Play Store, Firebase). We can have multiple upload jobs dependent on different artifacts. Looks roughly like this:
[Workflow Example](https://user-images.githubusercontent.com/1346296/106616720-87927200-6576-11eb-8656-e26acc576748.png)

It works very well on cloud machines, but as soon as some of our jobs moved to self-hosted runners space started to become an issue. Currently we just manually cleaning up artifacts from machines after uploading, but it feels like this could be a built-in functionality of the action itself.

Proposal is to add a single parameter to both `@actions/upload-artifact` and `@actions/download-artifact`, which would create a `Post Run actions/upload-artifact@v2` akin to `@actions/checkout`, which will  delete the `path` from which artifact was uploaded or to which it was downloaded from the local filesystem.

```
      - name: Upload AppStore IPA archive
        uses: actions/upload-artifact@v2
        with:
          retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}
          name: ${{ env.APPSTORE_IPA_ARTIFACT_NAME }}
          path: ${{ env.APPSTORE_IPA_ARTIFACT_PATH }}
          if-no-files-found: error
          delete-local-artifact: true
```

This will yield ability to have completely zero-side effect invocation of both types of jobs and help with space management.
Let me know what do you think of this proposal.

**Version**
- [ ] V1
- [x] V2

**Environment**
- [x] self-hosted
- [ ] Linux
- [ ] Windows
- [ ] Mac

**Screenshots**
[Workflow Example](https://user-images.githubusercontent.com/1346296/106616720-87927200-6576-11eb-8656-e26acc576748.png)

**Run/Repo Url**
If applicable, and if your repo/run is public, please include a URL so it is easier for us to investigate.

**How to reproduce**
If applicable, add information on how to reproduce the problem.

**Additional context**
Note that this is different from similar issues in this repo like https://github.com/actions/upload-artifact/issues/45, which want to limit artifact retention on the github servers. This is specifically the case for the local filesystem of the jobs.
