### ISSUE TITLE
The documentation says that relative paths are allowed, but they aren’t

### ISSUE THREAD

**Issue by leafac** [actions/upload-artifact#176]
**Describe the bug**

Compare [the documentation](https://github.com/actions/upload-artifact/blob/ea3d524381d563437a7d64af63f3d75ca55521c4/README.md#upload-using-multiple-paths-and-exclusions):

> Relative and absolute file paths are both allowed.

To [what actually happens](https://github.com/courselore/courselore/runs/1906616038?check_suite_focus=true):

```yaml
  with:
    path: ../courselore.zip
```

```
Error: Invalid pattern '../courselore.zip'. Relative pathing '.' and '..' is not allowed.
```

**Version**
- [ ] V1
- [x] V2

**Environment**
- [ ] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

**Screenshots**

**Run/Repo Url**
If applicable, and if your repo/run is public, please include a URL so it is easier for us to investigate.

**How to reproduce**
If applicable, add information on how to reproduce the problem.

**Additional context**

**Comment by hannesa2** [comment]
Same here 

```
      - name: Upload
        uses: actions/upload-artifact@v2.2.3
        with: 
          name: ios_dist.tgz
          path: ../viro/ios/dist/
```

shows me

<img width="677" alt="image" src="https://user-images.githubusercontent.com/3314607/115947131-e73d5100-a4c5-11eb-9513-f477a8960d4c.png">

**Comment by flavienbwk** [comment]
Same problem for me.

**Comment by jjhartmann** [comment]
I'm running into this error as well.

**Comment by ghuber-aarete** [comment]
I have the same problem.

**Comment by o01eg** [comment]
Would be nice if it will be fixed.

**Comment by RadxaYuntian** [comment]
Currently I have to use the following workaround to upload Debian package, which is created in parent folder by default:
```
      - name: Workaround actions/upload-artifact#176
        run: |
          echo "artifacts_path=$(realpath ..)" >> $GITHUB_ENV
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: |
            ${{ env.artifacts_path }}/*.deb
```
