### ISSUE TITLE
upload files with specific file extensions

### ISSUE THREAD

**Issue by graysuit** [actions/upload-artifact#178]
Hi guys,
Do anyone know how do I upload files with specific file extensions using upload artifact task using github ci ? I am trying to zip only files which ends with `.exe`.

I have used following documentations:
https://github.com/actions/upload-artifact/issues/3#issuecomment-524442814
 https://github.com/actions/upload-artifact

But builds still fails:
https://github.com/DarkSecDevelopers/RunSomeAware/blob/main/.github/workflows/Csharp_Compiler.yml
https://github.com/DarkSecDevelopers/RunSomeAware/actions

And here codes I tried:
`path: *.exe`
`path: ?.exe`
`path: RunSomeAware.exe,Icon.exe,Assembly_Changer.exe,Run_As_Admin.exe,Optimize.exe`

Currently I am compiling all executables to a folder and then upload that folder.

```yaml
name: Csharp Compiler csc.exe
on: [push]
env:
  csc: C:/Windows/Microsoft.NET/Framework/v2.0.50727/csc.exe
  csc4: C:/Windows/Microsoft.NET/Framework/v4.0.30319/csc.exe
  
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}

      run: mkdir RunSomeAware_Releases && ${{env.csc}} /out:RunSomeAware_Releases/RunSomeAware.exe RunSomeAware.cs && ${{env.csc}} /out:RunSomeAware_Releases/Assembly_Changer.exe RunSomeAware.cs Examples\Resources\AssemblyInfo.cs  && ${{env.csc}} /out:RunSomeAware_Releases/Icon.exe -win32icon:Examples\Resources/icon.ico RunSomeAware.cs  && ${{env.csc}} /out:RunSomeAware_Releases/Optimize.exe -optimize+ RunSomeAware.cs   && ${{env.csc4}} /out:RunSomeAware_Releases/Run_As_Admin.exe -win32manifest:"Examples\Resources/RunSomeAware.manifest" RunSomeAware.cs   

    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
       name: Releases
       path: RunSomeAware_Releases
```
