### ISSUE TITLE
Upload wrong thing when using mulitple paths

### ISSUE THREAD

**Issue by animalize** [actions/upload-artifact#179]
**Describe the bug**
When using these paths:
```yaml
          path: |
            ./dist/*.tar.gz
            ./wheelhouse/*.whl
            !./wheelhouse/*b*
```
The `dist` folder has a file `1.tar.gz`
The `wheelhouse` folder has two files: `a.whl`, `b.whl`

Then a file (or folder) `dist` is wrongly uploaded.

**Version**
- [ ] V1
- [x] V2

The workaround is uploading files separately:
```yaml
      - uses: actions/upload-artifact@v2
        with:
          name: pyzstd-files
          path: dist/*.tar.gz

      - uses: actions/upload-artifact@v2
        with:
          name: pyzstd-files
          path: |
            wheelhouse/*.whl
            !wheelhouse/*b*
```
