### ISSUE TITLE
Linebreaks in artifact name cause an "Unexpected response"

### ISSUE THREAD

**Issue by YellowAfterlife** [actions/upload-artifact#183]
**Describe the bug**
Including linebreaks in your artifact name causes unusual state where the build errors out but artifact is still uploaded (albeit without linebreaks)

**Version**
- [ ] V1
- [x] V2

**Environment**
- [ ] self-hosted
- [ ] Linux
- [x] Windows
- [ ] Mac

**Screenshots**
![image](https://user-images.githubusercontent.com/731492/111704989-a6a84300-8848-11eb-8033-2d61670d7191.png)

**Run/Repo Url**
https://github.com/YAL-GameMaker/steamworks.gml/actions/runs/666009729

**How to reproduce**
If applicable, add information on how to reproduce the problem.
```yaml
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: |
            line 1
            line 2
          path: ./file
```

**Additional context**
Pretty low-priority if anything - I was testing what I could and could not do to make artifact labels more readable, and figured that I'd try a linebreak since it wasn't on the forbidden character list
