### ISSUE TITLE
EACCES: permission denied, scandir

### ISSUE THREAD

**Issue by smac89** [actions/upload-artifact#192]
**Describe the bug**
Using a glob that happens to come across a folder not owned by the current user, causes the upload task to fail.

**Version**
- [x] V2

**Environment**
- [x] Linux

**Screenshots**
![ArcoLinux_2021-04-19_15-41-57](https://user-images.githubusercontent.com/8305511/115307064-f028ce00-a125-11eb-93b6-21db84bc66d1.png)

**How to reproduce**
```yaml
- name: Upload root
  if: always()
  uses: actions/upload-artifact@v2
  with:
    name: root-logs@${{ github.sha }}
    path: |
      /root/build/**/*-log.gz
    retention-days: 3
```

**Additional context**
I did a little digging, and the offending code is coming from `@actions/glob` which has been reported [here](https://github.com/actions/toolkit/issues/775). Just wanted to bring it to your attention as well.

**Comment by luillyfe** [comment]
any updates here??
I am getting an error when uploading files to gcloud storage

**Comment by kachkaev** [comment]
Same issue here when trying to include a Postgres Docker volume:

```yaml
- uses: actions/upload-artifact@v2
  if: ${{ failure() }}
  with:
    name: my-stuff
    path: stuff
```

```txt
Run actions/upload-artifact@v2
Error: EACCES: permission denied, scandir '/home/runner/work/repo-name/repo-name/stuff/docker-volumes/postgres/data'
```

Supplementing `path: stuff` with `!glob` does not seem to help:

```yml
    path: |
      stuff
      !stuff/docker-volumes/postgres
```

Looks like directory scanning still touches files with too few permissions.

My current workaround is to explicitly avoid `stuff/docker-volumes`. However, this means that I have to update `path` every time there is a new subfolder or a file in `stuff`.

```yml
    path: |
      stuff/a
      stuff/b
      stuff/c
```

**Comment by silverqx** [comment]
The same here, I'm trying to do something like this:
```
    - uses: actions/upload-artifact@v3
      with:
        name: mysql_after
        path: /var/lib/mysql
```

My current workaround for this is:
```
    - name: Prepare files
      run: |
        mkdir ./tmp
        sudo cp -r /var/lib/mysql ./tmp
        sudo chown -R runner:runner ./tmp
```

And after that upload the `./tmp` folder instead.

Would be nice to have the __user__ or __sudo__ parameter.
