### ISSUE TITLE
Question: Are the sub-folders also uploaded ?

### ISSUE THREAD

**Issue by cmoulliard** [actions/upload-artifact#194]
## Question

Are the sub-folders also uploaded when we use the following syntax and dir structure ?

```yaml
name: Upload jar file created
uses: actions/upload-artifact@v2
with:
    name: release-manager-jar-files
    path: |
         ${{ github.workspace }}/target/quarkus-app/lib
```

ls -la 
```
 tree ./target/quarkus-app/lib/
./target/quarkus-app/lib/
├── boot
│   ├── io.quarkus.quarkus-bootstrap-runner-1.13.2.Final.jar
│   ├── io.quarkus.quarkus-development-mode-spi-1.13.2.Final.jar
│   ├── io.smallrye.common.smallrye-common-io-1.5.0.jar
│   ├── org.graalvm.sdk.graal-sdk-21.0.0.jar
│   ├── org.jboss.logging.jboss-logging-3.4.1.Final.jar
│   ├── org.jboss.logmanager.jboss-logmanager-embedded-1.0.9.jar
│   └── org.wildfly.common.wildfly-common-1.5.4.Final-format-001.jar
└── main
    ├── aopalliance.aopalliance-1.0.jar
    ├── com.atlassian.event.atlassian-event-3.0.0.jar
    ├── com.atlassian.httpclient.atlassian-httpclient-api-2.0.0.jar
...
```
