### ISSUE TITLE
`working-directory` is not taken into account

### ISSUE THREAD

**Issue by wsw70** [actions/upload-artifact#196]
**Describe the bug**

**Version**
- [ ] V1
- [x ] V2

**Environment**
- [ ] self-hosted
- [ ] Linux
- [x ] Windows
- [ ] Mac

**How to reproduce**
The `working-directory` entry is not taken into account, and despite being in that directory during the job, a full path must be provided.

```
name: note
on: push
jobs:
  cli:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./cli
    steps:
      - uses: actions/checkout@master
      - run: go build -v
      - run: dir
      - name: upload cli.exe
        uses: actions/upload-artifact@v2
        with:
          name: cli.exe
          path: cli.exe
```

This leads to

![image](https://user-images.githubusercontent.com/1345886/116773912-f473b600-aa58-11eb-90a7-5f53c3794cea.png)

By changing `path: cli.exe` to `path: cli/cli.exe` (i.e. providing the full path) the issue is fixed.
