### ISSUE TITLE
The `env` vars aren't all being expanded in Actions Stanza

### ISSUE THREAD

**Issue by matt-palermo-optum** [actions/upload-artifact#213]
**Describe the bug**
upload/download files doesn't seem to honor environment vars.  It works in bash `run:` just fine.  The `env` vars aren't all being expanded in an Actions Stanza, but they are in straight bash.

VAR:
```
env:
  plan_outfile_name: "${{ github.event.inputs.env }}_${{ github.event.inputs.dc }}_${GITHUB_RUN_ID}_${GITHUB_RUN_NUMBER}.plan"
```

BASH:
```
- name: TEST ENV
  run: |
    echo "env.plan_outfile_name: ${{env.plan_outfile_name}}"
```
![Screen Shot 2021-06-01 at 3 33 17 PM](https://user-images.githubusercontent.com/82891848/120380164-d1098880-c2ee-11eb-91fb-8a0efe3cc9ab.png)

In an Actions Stanza:
```
- name: 'Upload Plan Outfile'
  id: plan-upload-planfile
  uses: actions/upload-artifact@v2
  with:
    name: "${{env.plan_outfile_name}}"
    path: "./infrastructure/${{env.plan_outfile_name}}"
```
![Screen Shot 2021-06-01 at 3 35 04 PM](https://user-images.githubusercontent.com/82891848/120380259-f39ba180-c2ee-11eb-962e-d3e44a4536dd.png)

**Version**
- [ ] V1
- [X] V2

**Environment**
- [ ] self-hosted
- [X] Linux
- [ ] Windows
- [ ] Mac

**Screenshots**

**Run/Repo Url**
private repo... sorry...  but the code above to show the issue is 100% copy 'n' paste from one of our workflows.

**How to reproduce**
Put the above stuff in one of your workflows and run it.

**Additional context**
N/A/
