### ISSUE TITLE
"Error: Argument list too long" when uploading a single file

### ISSUE THREAD

**Issue by jketcham** [actions/upload-artifact#214]
**Describe the bug**
I'm not sure exactly what is causing this behaviour, but when I try to upload a single file (that has the `terraform plan` output from multiple invocations), this error occurs during the upload step, and then again on action cleanup.

The relevant steps in my workflow are here:

```yaml
    - name: Terraform Plan
      if: steps.configs.outputs.present == 'true'
      id: plan
      run: |-
        cat files.txt | xargs -L 1 -I % sh -c '(cd % && terraform plan -no-color >> ${{ runner.temp }}/plan.txt)'

        echo 'PLAN<<EOF' >> $GITHUB_ENV
        cat ${{ runner.temp }}/plan.txt >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
      continue-on-error: true

    - name: Archive plan
      uses: actions/upload-artifact@v2
      with:
        if-no-files-found: ignore
        name: terraform-plan-${{ github.sha }}
        path: ${{ runner.temp }}/plan.txt
```

The `plan` ends up being built 12 times in this case, with each output getting added to the temp `plan.txt` file.

Could it be that adding the output to an ENV variable (so I can access it in another step that posts it as a comment to Pull Requests) is causing this issue? Or could it be that I am using a file in the temp directory? Any help is greatly appreciated!

**Version**
- [ ] V1
- [x] V2

**Environment**
- [ ] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

**Screenshots**
<img width="380" alt="Screen Shot 2021-06-01 at 5 25 55 PM" src="https://user-images.githubusercontent.com/1548556/120406099-eedee980-c2fe-11eb-83c8-8458c226880b.png">

**How to reproduce**
Not sure.

**Additional context**
N/A
