### ISSUE TITLE
Unable to locate the upload artifact path

### ISSUE THREAD

**Issue by devevignesh** [actions/upload-artifact#215]
**Describe the bug**
I'm trying to upload the index.html file in ${{ github.workspace }} directory and use path reference in shell script but it is throwing an error "No such file or directory". 

**Version**
- [ ] V1
- [x] V2

**Environment**
- [ ] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

**Run/Repo Url**
*error*: https://github.com/devevignesh/test-app-build/runs/2734949995?check_suite_focus=true#step:5:19

*workflow*: https://github.com/devevignesh/test-app-build/runs/2734949995?check_suite_focus=true

*action*: https://github.com/devevignesh/cp-to-repo/blob/main/entrypoint.sh

**Comment by josiext** [comment]
You should put this code

```
    name: Deploy
    needs: job_1
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Push static files
        run: |
          cd ${{ github.workspace }}
          ls
```

after the built not in another job
