### ISSUE TITLE
Action doesn't seem to read environment variables inside a container

### ISSUE THREAD

**Issue by parizmendi** [actions/upload-artifact#216]
**Describe the bug**
When calling the action inside a container with `container.env` variables, the action doesn't seem to be able to use them.

**Version**
- [ ] V1
- [X] V2

**Environment**
- [ ] self-hosted
- [X] Linux
- [ ] Windows
- [ ] Mac

**Screenshots**
This is the output of the action, where it only gets the global `env` variables:
![image](https://user-images.githubusercontent.com/72130275/121154328-2d1c6180-c847-11eb-8ff2-5b8a0e7cceb8.png)

**Run/Repo Url**
The repo is private.

**How to reproduce**
This is a snippet of how the action its configured:
```
name: Android workflow
on: [push]
env:
  FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
  FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
  MATCH_ENTERPRISE_PASSWORD: ${{ secrets.MATCH_ENTERPRISE_PASSWORD }}
  CIRCLE_BUILD_NUM: 10
jobs:
  build:
    name: Build
    environment: some_env
    runs-on: ubuntu-latest
    container:
      image: circleci/android:api-29-ndk
      env:
        API_URL: <some var>
        NODE_ENV: <some var>
        APP_NAME: <some var>
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      [... Build app ...]
      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-${{ env.APP_NAME }}-${{ env.NODE_ENV }}
          path: android/app/build/outputs/bundle/release/app-release.apk
          retention-days: 2
```
The action its able to read the variables from `env`, but not the ones from `jobs[*].container.env`, so the variables inside the upload-artifact name don't get resolved and name ends in just a plain `android--`
