### ISSUE TITLE
Feature request: Output for was uploaded

### ISSUE THREAD

**Issue by rnett** [actions/upload-artifact#220]
With the don't fail on missing file behavior, it would be nice to have whether the file was uploaded (i.e. did it exist) as an output, for use in later jobs and steps that depend on that artifact.

**Comment by dlmiles** [comment]
For me this might look like:

```
- name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-name-docs
        path: dist/my-file.tar.gz
      outputs:
        key: fixed-string
        another: can ${{ maybe }} use expression ${{ env.foo }} as well in value but key is fixed string
```
