### ISSUE TITLE
Access to github actions specific environment variables

### ISSUE THREAD

**Issue by end2endzone** [actions/upload-artifact#231]
**Describe the bug**
I am unable to refer to environment variables using the `${{env.name}` syntax. More specifically, the environment variable `ImageOS` that is automatically created by Github when running a workflow.

**Version**
- [ ] V1
- [x] V2

**Environment**
- [ ] self-hosted
- [x] Linux
- [x] Windows
- [x] Mac

**Screenshots**
Usage:
```
    - name: Archive installation packages
      uses: actions/upload-artifact@v2
      with:
        name: bin2cpp-packages-${{env.ImageOS}}
        path: build/bin2cpp-${{env.BIN2CPP_VERSION}}-*.*
```

Output:
```
Run actions/upload-artifact@v2
  with:
    name: bin2cpp-packages-
    path: build/bin2cpp-2.4.0-*.*
    if-no-files-found: warn
  env:
    PlatformToolset: v140
    Platform: x64
    Configuration: Release
    pythonLocation: C:\hostedtoolcache\windows\Python\3.9.5\x64
    GIT_REPOSITORY: bin2cpp
    GIT_BRANCH: master
    GITHUB_WORKFLOW: Windows
    UNITTEST_REPORT_PATH: D:\a\bin2cpp\bin2cpp\build\bin\Release\bin2cpp_unittest.x64.release.xml
    BIN2CPP_VERSION: 2.4.0
```

**Run/Repo Url**
Repo: https://github.com/end2endzone/bin2cpp
Workflow runs: [macos](https://github.com/end2endzone/bin2cpp/actions/runs/974539587), [linux](https://github.com/end2endzone/bin2cpp/actions/runs/974539588) and [windows](https://github.com/end2endzone/bin2cpp/actions/runs/974539593)

**How to reproduce**
I call the action as specified above in "usage". Looking at the output, we see that `name` is resolved as `bin2cpp-packages-`  instead of the expected string `bin2cpp-packages-ubuntu20`. It is missing the `${{env.ImageOS}}` concatenation. I was under the impression that I could refer to any environment variables as specified in your readme [here](https://github.com/actions/upload-artifact#environment-variables-and-tilde-expansion) but in your example, `name` might be a custom variable.

**Additional context**
Looking at the "usage" reference above, I am able to refer to my "custom" environment variable `BIN2CPP_VERSION` without a problem. This variable is created manually in a previous step with something like `echo BIN2CPP_VERSION=2.4.0 >> $GITHUB_ENV`. However, I am unable to reference other environment variables such as the one provided by Github Actions.

I was able to confirm that `ImageOS` environment is actually created using the following action in Linux and macOS :
```
    - name: List environment variables for debugging
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: bash
      run: |
        env
```
or on Windows,
```
    - name: List environment variables for debugging
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: cmd
      run: |
        set
```

Note: This issue seems to be related to #216 but I am not certain thus creating a new issue. #216 is about specific docker variables which I do not use.

**Comment by end2endzone** [comment]
I am afraid that only the variables following the `env:` can be accessed. In my example, that would be
```
  env:
    PlatformToolset: v140
    Platform: x64
    Configuration: Release
    pythonLocation: C:\hostedtoolcache\windows\Python\3.9.5\x64
    GIT_REPOSITORY: bin2cpp
    GIT_BRANCH: master
    GITHUB_WORKFLOW: Windows
    UNITTEST_REPORT_PATH: D:\a\bin2cpp\bin2cpp\build\bin\Release\bin2cpp_unittest.x64.release.xml
    BIN2CPP_VERSION: 2.4.0
```

It might also be possible that when an action has a `shell:` specified, then more environment variables are created by the workflow. Another hypothesis is these shell-specific additional variables are not persisted across all the following actions. I have not test this but this would explain why only "custom" environment variables can be resolved by the action `actions/upload-artifact@v2`.

Does anyone know how to get access to variables such as `ImageOS` ? I do require this to make sure that my artifacts do not have the same name across all my workflows. I do use 1 workflow per OS to easily handle OS specific actions and commands.

I might try to add a `shell:` element following `uses: actions/upload-artifact@v2` in hope that more environment variables are available but I have not seen anywhere in the documentation that such a use case is supported by upload-artifact@v2.

A possible workaround might be to "copy" `ImageOS` as a custom manually-created environment variable making it available in the action with something such as :
```
    - name: Make ImageOS env var available outside of shells
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: bash
      run: |
        echo ImageOS=$ImageOS>> $GITHUB_ENV
```
but this is an ugly workaround and does not scale up when multiple other environment variables are required.
