### ISSUE TITLE
No files were found with the provided path: build. No artifacts will be uploaded.

### ISSUE THREAD

**Issue by bkiac** [actions/upload-artifact#232]
**Describe the bug**
I'm following the examples but I keep getting this error message: `No files were found with the provided path: build. No artifacts will be uploaded.`

**Version**
- [ ] V1
- [x] V2

**Screenshots**
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/24522620/123978617-4b95f880-d9c0-11eb-81e2-7d79ff7b4372.png">

**How to reproduce**

Try to upload a folder

```yml
- name: Archive bundle
  uses: actions/upload-artifact@v2
  with:
    name: bundle
    path: build
    if-no-files-found: error
```

**Additional context**

I've found a [similar issue on StackOverflow](https://stackoverflow.com/questions/66998799/no-files-were-found-with-the-provided-path-build-no-artifacts-will-be-uploaded) but the solution didn't work for me.

**Comment by RDKRACZ** [comment]
Maybe try `path: ./build` or `path: ./build/*`.

**Comment by bkiac** [comment]
`./build`, `./build/*` don't work. The [docs](﻿﻿https://docs.github.com/en/actions/advanced-guides/storing-workflow-data-as-artifacts#uploading-build-and-test-artifacts) use it without an asterisk. Months later, I still can't make this work, on any project or repo, I'm really confused because no one else seems to have this issue.

**Comment by bkiac** [comment]
I found the problem, the upload-artifact action does not respect the `working-directory` setting

**Comment by alanbosco003** [comment]
Hello can you please describe little more? 
where to use working-directory? am new to github actions

**Comment by bkiac** [comment]
@alanbosco003 I got the error because I used a `working-directory` default and relative path but you have to add a path from root:

```yml
build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./react
    steps:
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - name: Archive build artifact
        uses: actions/upload-artifact@v2
        with:
          name: react-bundle
          path: react/react-bundle # ./react-bundle, ./react-bundle/*, react-bundle do not work
          if-no-files-found: error
```

**Comment by alanbosco003** [comment]
`jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get.
      - run: flutter build apk --debug
      - uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: build\app\outputs\flutter-apk\app-debug.apk`

**Comment by mitiko** [comment]
> @konradpabjan Any thought on adding `workingDirectory` support to actions/upload-artifact ?

Seems like a good change for a 3.2 release :)

**Comment by arpit999** [comment]
In my case (Android Project) I need to specify the app as the root directory.

`app/build/reports/lint-results-debug.html`

**Comment by socketopp** [comment]
```
my-project/
├ src/
│ ├ lib/
│ │ ├ server/
│ │ │ └ [your server-only lib files]
│ │ └ [your lib files]
│ ├ params/
│ │ └ [your param matchers]
│ ├ routes/
│ │ └ [your routes]
│ ├ app.html
│ ├ error.html
│ ├ hooks.client.js
│ └ hooks.server.js
├ static/
│ └ [your static assets]
├ tests/
│ └ [your tests]
├ package.json
├ svelte.config.js
├ tsconfig.json
└ vite.config.js
```

Is `my-project` here the working directory when using SvelteKit? I am currently getting the same issue. Here is my deploy script


```
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: build
        env:
          BASE_PATH: '/socketopp.github.io'
        run: |
          npm run build
          touch build/.nojekyll

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: 'build/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
```

**Comment by Premsing** [comment]
No files were found with the provided path: cypress/videos. No artefacts will be uploaded.
```
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
```
I even changed my IF condition to always(), but no videos were in the specified folder.

**Comment by Rod-in-NM** [comment]
> I found the problem, the upload-artifact action does not use the `working-directory` setting

Thank you for this. I'm having the same issue, but with a Windows server. I assume that the `working-directory` isn't set as I thought it would be. I'll experiment with it.

**Comment by colossus06** [comment]
I have a default working directory:

```sh
defaults:
  run:
   working-directory: ./nodejs-app
```
Still couldn't upload the artifact. 
After reading the comments, fixed it by providing the exact path:

```sh
      - name: prepare the staging env
        run: mkdir test-results && cp test-report.html test-results
        
      - uses: actions/upload-artifact@v3
        if: success() || failure() 
        with:
          name: test-report.html
          path: ./nodejs-app/test-results
```

**Comment by abdifitahabdulkadir** [comment]
this works to me perfectly all the time and with artfact@v1 and 2

```
 - run: flutter build apk 
      - uses: actions/upload-artifact@v2
        with:
          name: Mono-release-apk
          path: build/app/outputs/apk/release/app-release.apk``
```

**Comment by peter-byun** [comment]
For anyone uploading hidden files, [hidden files are ignored by default](https://github.com/actions/upload-artifact?tab=readme-ov-file#uploading-hidden-files). You should opt-in to include hidden files when uploading an artifact.

**Comment by batboon** [comment]
> I got the error because I used a `working-directory` default and relative path but you have to add a path from root:

This was the issue for my case, thank you very much T^T

**Comment by floriancochard** [comment]
For anyone running into this issue and working with a Next app, adding ```include-hidden-files``` combined with an absolute path from the root of the repo worked for me:
```
name: CI
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    steps:
      - name: Upload artifacts for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: |
            ${{ github.workspace }}/.next
            ${{ github.workspace }}/.next/standalone
            ${{ github.workspace }}/.env.local
          include-hidden-files: true
          if-no-files-found: error
          compression-level: 9

# rest of your build logic

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: next-build

# rest of your deploy logic
```
