### ISSUE TITLE
Upload build artifact not working

### ISSUE THREAD

**Issue by gabenotgave** [actions/upload-artifact#236]
I'm trying to build my .NET Core application using GitHub actions (which I was able to achieve), but I also want to store the artifacts from the build in a folder in my repository for deployment. I'm trying to upload (which I think is what I should be do rather than download) after the build. Here is my YAML file:
```
name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore src/Lambgoat.Web.sln
    - name: Build
      run: dotnet build src/Lambgoat.Web.sln --no-restore
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: test
        path: artifacts
```
But it puts nothing in the artifacts folder. This is my first time using GitHub actions and would appreciate any help.

**Comment by RDKRACZ** [comment]
I think your path is incorrect. I'm not sure where your app is stored after build but you should know if you build it on a local machine.
If you don't know you can try to add `pwd; ls` after your build script (so `run: dotnet build src/Lambgoat.Web.sln --no-restore; pwd; ls` and then look at the log to see your files and change the path ex.
```
uses: actions/upload-artifact@v2
      with:
        name: test
        path: ./myapp

``` 
or `path: ./myapp/app.exe`
