### ISSUE TITLE
Error: Create Artifact Container failed: getaddrinfo EAI_AGAIN pipelines.actions.githubusercontent.com

### ISSUE THREAD

**Issue by bluca** [actions/upload-artifact#239]
**Describe the bug**
```
Run actions/upload-artifact@v2
  with:
    name: test-logs
    path: build/meson-logs/testlog.txt
    if-no-files-found: warn
With the provided path, there will be 1 file uploaded
Create Artifact Container - Attempt 1 of 5 failed with error: getaddrinfo EAI_AGAIN pipelines.actions.githubusercontent.com
Create Artifact Container - Attempt 2 of 5 failed with error: getaddrinfo EAI_AGAIN pipelines.actions.githubusercontent.com
Create Artifact Container - Attempt 3 of 5 failed with error: getaddrinfo EAI_AGAIN pipelines.actions.githubusercontent.com
Create Artifact Container - Attempt 4 of 5 failed with error: getaddrinfo EAI_AGAIN pipelines.actions.githubusercontent.com
Create Artifact Container - Attempt 5 of 5 failed with error: getaddrinfo EAI_AGAIN pipelines.actions.githubusercontent.com
Error: Create Artifact Container failed: getaddrinfo EAI_AGAIN pipelines.actions.githubusercontent.com
```

**Version**
- [ ] V1
- [x] V2

**Environment**
- [ ] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

**Run/Repo Url**
https://github.com/systemd/systemd/pull/20321/checks?check_run_id=3182341897
https://github.com/systemd/systemd/pull/20321/commits/2afe3e1c5ccdd02f5d11ca688d28b6b7fbe86745

**How to reproduce**
Retried a few times, always fails with the same EAI_AGAIN message.

```
name: Unit tests
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        run_phase: [GCC, GCC_ASAN_UBSAN, CLANG, CLANG_ASAN_UBSAN]
    steps:
      - name: Repository checkout
        uses: actions/checkout@v1
      - name: Install build dependencies
        run: sudo -E .github/workflows/unit_tests.sh SETUP
      - name: Build & test (${{ matrix.run_phase }})
        run: sudo -E .github/workflows/unit_tests.sh RUN_${{ matrix.run_phase }}
      - name: Archive test results
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: test-logs
          path: build/meson-logs/testlog.txt
```
