### ISSUE TITLE
Uploading multiple artifacts with the same name silently quashes each other

### ISSUE THREAD

**Issue by Julian** [actions/upload-artifact#24]
I had a matrix build doing this:

```
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [pypy2, pypy3, 3.7]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools setuptools_scm wheel
    - name: Create packages
      run: python setup.py sdist bdist_wheel
    - uses: actions/upload-artifact@master
      with:
        name: dist
        path: dist

```

i.e. building an artifact using each of 3 Python versions, and where the 3 versions were all creating the same file and uploading it as the same name.

Might be nice for this to error out saying an artifact with the given name was already uploaded during this run of the workflow.

**Comment by nulano** [comment]
+1

A potential workaround is to specify the python version in the artifact name, i.e. `name: dist-${{ matrix.python-version }}`.

**Comment by johnterickson** [comment]
@Julian - Potentially makes sense to bail when artifact name is already in use. What's your thought on what should happen on a job retry?
1.  Artifact has a union of files from first attempt and second attempt (last-writer wins)
2.  Artifact is deleted and recreated from scratch.

**Comment by Julian** [comment]
I think definitely bailing is right yeah.

For simple cases I guess you can even detect ahead of time statically if there are multiple outputs the workflow is going to generate, but maybe that's too annoying to do in general and you just bail when you try to generate the second one at runtime.

For retry... I'm sure different folks will have different expectations there, me personally, I'm OK with 2 there and you just lose previous runs, but if you're going to preserve them I think it has to be separate at least -- like it should be brutally obvious which run produced which artifact, such that even if a path through the workflow changed and you produced a separate set of outputs, you shouldn't see the union all in one place in a way that doesn't make it obvious which run it came from.

I.e. an algorithm like:

the first step in a retry is to go rename all previously existing artifacts to {artifact}-{previousRunID}.

Not sure how feasible that is but yeah seems a bit icky to me to think you can end up with mixed artifacts and not know where they came from -- but yeah again, I'd personally not really need that functionality, I don't mind if runs always wipe out previous artifacts.

(And thanks for the response! Much appreciated.)

**Comment by alexkrytsky** [comment]
@Julian I'd like to have the same behavior. Wipe and recreate would work for me as well.
I think some people would also want to have an accumulation of artifacts. I like how it's implemented with logs for multiple runs/retries. It's just a drop down and you select attempt and it will show you logs for that run. So same might be here, it'd be just a different container. Instead of renaming each file, you just add another container with RunID as an identifier. 

Looking forward to having this feature out with support for overriding same name artifact!

**Comment by AraHaan** [comment]
Sadly this is somewhat can be breaking because for me, I want to have artifact of same name in a matrix build for macos, linux, and windows where they would essentially be converted into a single artifact with all of the files from each runner in the packaged folder being zipped into the same artifact.

**Comment by bogdanbarna** [comment]
> Sadly this is somewhat can be breaking because for me, I want to have artifact of same name in a matrix build for macos, linux, and windows where they would essentially be converted into a single artifact with all of the files from each runner in the packaged folder being zipped into the same artifact.

You can have a separate job for bundling all platform artifacts into a single one. Something along the lines of
```yaml
job1:
...
strategy:
  matrix:
    platform: [windows, ubuntu, macos]
- upload artifact
   name: foo-${{ matrix.platform }}
...
job2:
...
- download windows artifact
   name: foo-windows
- download ubuntu artifact
  name: foo-ubuntu
- download macos artifact
  name: foo-macos
- bundle artifacts
  run: zip artifact.zip foo-{windows,ubuntu,macos}
```
