### ISSUE TITLE
Doesn't support variables?

### ISSUE THREAD

**Issue by RDKRACZ** [actions/upload-artifact#242]
**Describe the bug**
I create a shell variable - I want to upload only one file.
```
file=$(ls |head -n 1);
```
... Then I want to use this variable in the path.
```
actions/upload-artifact@v2.2.4
      with:
        name: ${{ github.event.repository.name }}
        path: build/libs/"${file}"
```
**Version**
- [x] V2

**Environment**
- [x] Linux
