### ISSUE TITLE
Creating variable number of artifacts

### ISSUE THREAD

**Issue by arielelkin** [actions/upload-artifact#245]
Currently, this will upload the entire contents of `path/to/artifacts` as a single zip file:

```yml
- uses: actions/upload-artifact@v2
  with:
    name: my-artifact
    path: path/to/artifacts/
```

It would be nice if you could specify that you want each file in that directory to be uploaded separately, for example:

```yml
- uses: actions/upload-artifact@v2
   with:
     name: my-artifact
     path: path/to/artifacts/
     upload-each-artifact-separately: true # 😀
```

The benefit is that you then wouldn't have to download a big zip file of artifacts when you just need one artifact.
