### ISSUE TITLE
Error: Unrecognized if-no-files-found input. Provided: . Available options: warn,error,ignore

### ISSUE THREAD

**Issue by zivkovic** [actions/upload-artifact#255]
**Describe the bug**
I'm running a self hosted runner and the workflow job is ran in a container. When a test fails and should upload the screenshots, the following error is displayed. As seen in screenshot below, I have set the `if-no-files-found` to `ignore`, but error still displays as if this was configured incorrectly.

**Version**
- [ ] V1
- [x] V2

**Environment**
- [x] self-hosted
- [ ] Linux
- [ ] Windows
- [ ] Mac

**Screenshots**

The displayed error message:
![image](https://user-images.githubusercontent.com/2651524/136757019-b0b0b6e4-b3d2-49d3-a8a6-942bfc08e893.png)

The start of the workflow:
![image](https://user-images.githubusercontent.com/2651524/136757781-e4a5b148-8efe-4644-8ade-1b3d15c41f97.png)

If you require more info, let me know.

**Comment by aljazkosir** [comment]
I'm also facing the same issue

**Comment by vafanasy** [comment]
We have similar issue, but as warning and looks like this "if-no-files-found" isn't working.
`Warning: Unexpected input(s) 'if-no-files-found', valid inputs are ['name', 'path']
with:
    name: test-results
    path: target/surefire-reports
    if-no-files-found: ignore
Error: Path does not exist /some_path/target/surefire-reports`

**Comment by shanepowell-ast** [comment]
I just want to add.. I'm experiencing this same issue.  Also on a self-hosted linux based runner.
Nothing I do seems to resolve the error.  I've tried leaving the if-no-files-found field out, specified an explicit value, with and with out quotes.  Even tried a numerical index.  Tried @v2, @v3 and @main  They all seem to show the same issue.

**Comment by umutozd** [comment]
We are also experiencing this issue. Our configuration looks like the following:
```yaml
- uses: actions/upload-artifact@v3
  with:
    name: <artifact-name>
    path: |
      path/to/file1
      path/to/file2
      path/to/file3
```
and exactly the below error is printed once this action runs:
```
Error: Unrecognized if-no-files-found input. Provided: . Available options: warn,error,ignore
```

I have tried the below configuration too, with the same error message.
```yaml
- uses: actions/upload-artifact@v3
  with:
    name: <artifact-name>
    path: |
      path/to/file1
      path/to/file2
      path/to/file3
    if-no-files-found: warn
```

The odd thing is, the upload of files succeed. The problem is that this workflow looks to be failed because of this `if-no-files-found` issue.
