### ISSUE TITLE
actions/upload-artifact is not working as expected in 32-bit linux containers

### ISSUE THREAD

**Issue by flavorjones** [actions/upload-artifact#266]
**Describe the bug**

Similar to https://github.com/actions/cache/issues/675 and https://github.com/actions/checkout/issues/334, `upload-artifact@v2` isn't working in a 32-bit linux container.

The error message when attempting to use it from a 32-bit linux container is:

```
OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: no such file or directory: unknown
```

The full output is:

```
Run actions/upload-artifact@v2
  with:
    name: cruby-x86-linux-gem
    path: gems
    retention-days: 1
    if-no-files-found: warn
/usr/bin/docker exec  6c65795b7f4a06fad0d6439485ab16266042571414e024b1b5b1ca72d3cb1ea9 sh -c "cat /etc/*release | grep ^ID"
OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: no such file or directory: unknown
```

A sample job config is:

```yaml
jobs:
  myjob:
    runs-on: ubuntu-latest
    container:
      image: "i386/ubuntu:bionic"
    steps:
      - run: "script-to-create-the-artifact"
      - uses: actions/upload-artifact@v2
        with:
          name: "x86-linux-artifact"
          retention-days: 1
```

**Version**
- [ ] V1
- [x] V2

**Environment**
- [ ] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

Note: *32-bit* linux

**Screenshots**

![image](https://user-images.githubusercontent.com/8207/141502152-c381469d-ebbf-4ce4-b7f6-59f3e9f2a0b9.png)

**Run/Repo Url**

https://github.com/sparklemotion/nokogiri/runs/4183748133?check_suite_focus=true

**How to reproduce**

Provided above

**Additional context**

Similar to https://github.com/actions/cache/issues/675 and https://github.com/actions/checkout/issues/334
