### ISSUE TITLE
[feat req] Allow `retention-days` to be `0`

### ISSUE THREAD

**Issue by kolpav** [actions/upload-artifact#290]
### What would you like to be added?

Allow `retention-days` to be `0` meaning do not store artifacts after workflow run.

### Why is this needed?

- You have no use of artifacts after workflow run and you don't want them to take up space for 24h
- 24h duration seems arbitrary chosen
- 24h is too long to not hit your CI storage limit
- Available storage calculation is buggy or takes a while to update after hitting storage limit and deleting artifacts
- https://github.com/actions/upload-artifact/issues/5

-----

These solutions might be proposed but actually doesn't solve the problem with few points why I think they are not.

## Use UI

- You might not have permission to delete artifacts
- You have to go through all workflow runs without indication if it contains artifact or not
- You have to delete all artifacts one by one

## Use API

- Seems like an overkill for something I would argue should be native functionality
- You need to rely on API which might become obsolete or stop working

## Use action from marketplace

- I think this should be native functionality
- You need to choose "right" action which might become unmaintained

## This issue is duplicate

- I think I mentioned problems people are actually having by going through issues and threads on other sites
- I have found no suitable solution in other issues
- I think other relevant issues are worded poorly and making it seem they just don't know how to delete some specific artifact once when after reading into their problem more is they actually want what I described here

**Comment by praenubilus** [comment]
Can't believe it, the original issue was created 3 years ago and it still has no official action

**Comment by kolpav** [comment]
@praenubilus I share your disbelief. To be completely honest I wouldn't be surprised if this is "by design" or fix would be very hard to approve in github's chain of command because people would stop polluting their storage with useless artifacts used just to share data between jobs (build -> test -> deploy) it would decrease amount of ~~people~~customers

- upgrading to pro to increase their storage limit
- entering their payment information which makes them much easier to sell future products to
- maxing their monthly spending limit

but lets not jump to conclusions and wait for feedback.

**Comment by praenubilus** [comment]
@kolpav I hope the day it comes out I am still alive

**Comment by Koushikphy** [comment]
I was releasing nodejs application binary with GitHub workflow for different os and architecture. In the initial stage, I was testing different workflow patterns and quickly hit the quota limit. I don't really need the artifacts after the workflow is run and the artifacts are released. It's disappointing to see that it does not have the delete option when the workflow si complete.

**Comment by duaneking** [comment]
I *need* this functionality.

**Comment by DPatrickBoyd** [comment]
here is an example that I just got to work for deletion after a run is done.
secrets.GH_REPO_ACCESS_PAT is a PAT that I made and gave it the ability read repos and org stuff as well, not sure how important the scope is.
```
name: Test

on:
  workflow_run:
    branches: [main]
    workflows: [nonprod,prod,test]
    types:
      - completed
jobs:
  on-success:
    runs-on: ubuntu-latest
    name: Delete artifact
    if: github.event.workflow_run.head_branch == 'main' # feel free to take this out if you don't need it
    steps:
      - id: get-id
        run: | # grab the id of the artifact we just created
          echo "ARTIFACT_ID=$(gh api -H 'Accept: application/vnd.github+json'   ${{github.event.workflow_run.artifacts_url}} --jq .artifacts[].id)" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GH_REPO_ACCESS_PAT }}
      - run: |
          echo "artifact id is ${{ env.ARTIFACT_ID}}"
          echo "run url is ${{github.event.workflow_run.artifacts_url}}"
      - id: delete-artifact
        run: | # https://docs.github.com/en/rest/actions/artifacts?apiVersion=2022-11-28#delete-an-artifact
          gh api --method DELETE -H 'Accept: application/vnd.github+json' /repos/${{github.repository}}/actions/artifacts/${{env.ARTIFACT_ID}}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_REPO_ACCESS_PAT }}
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
```
