### ISSUE TITLE
[bug] upload-artifact does not respect the working directory

### ISSUE THREAD

**Issue by rodush** [actions/upload-artifact#294]
### What happened?

When the working directory for the whole job is changed via:

```yaml
...
defaults:
    run:
        working-directory: some-directory
```

and the path to artefact is specified as

```yaml
...
with:
    path: some-file.txt
```

then the Action fails to find the file.

### What did you expect to happen?

Upload Artifact action should respect the "working-directory" parameter, instead of trying to resolve file from the `github.workspace`

### How can we reproduce it?

Use the yaml snippets from the description above

### What version of the action are you using?

v2

### What are your runner environments?

linux
