### ISSUE TITLE
Wildcard for files in the root is not working

### ISSUE THREAD

**Issue by marcofranssen** [actions/upload-artifact#304]
### What happened?

When using following wildcard the whole repository is included in the artifact upload.

```yml
      - name: Dummy test
        run: |
          touch backend-attestations.txt
          touch web-attestations.txt
          touch traefik-attestations.txt

      - name: Upload attestations
        uses: actions/upload-artifact@v2.3.1
        with:
          name: attestations
          path: ./*-attestations.txt
```

When downloading the whole repository is included including `.git` folder and `.github` folder and all source code.

```yaml
      - name: Download attestations
        uses: actions/download-artifact@v3.0.0
        with:
          name: attestations

      - name: Debug
        run: |
          ls -ahl
```

### What did you expect to happen?

Only the 3 attestation files should be included in the uploaded artifact.

### How can we reproduce it?

```
name: Release Unstable Examples

on:
  push:
    branches:
      - main
    tags-ignore:
      - v*

jobs:
  upload:
    runs-on: [self-hosted, research]

    steps:
      - name: Check out code
        uses: actions/checkout@v2.4.0

      - name: Verify attestation
        run: |
          touch backend-attestations.txt
          touch web-attestations.txt
          touch traefik-attestations.txt

      - name: Upload attestations
        uses: actions/upload-artifact@v2.3.1
        with:
          name: attestations
          path: ./*-attestations.txt
  download:
    runs-on: [self-hosted, research]

    steps:
      - name: Download attestations
        uses: actions/download-artifact@v3.0.0
        with:
          name: attestations

      - name: Debug
        run: |
          ls -ahl
```

### What version of the action are you using?

v2.3.1

### What are your runner environments?

self-hosted, linux
