### ISSUE TITLE
[feat req] - enhance if-no-files-found 

### ISSUE THREAD

**Issue by codezninja** [actions/upload-artifact#306]
### What would you like to be added?

Support for `if-no-files-found` for some files to not fail completey

Lets say we are creating a generic step to upload files

```yaml
        uses: actions/upload-artifact@v2
        with:
          name: java-artifact
          path: |
            ${{ github.workspace }}/target/*.war
            ${{ github.workspace }}/target/*.jar
          if-no-files-found: error
```

I would like it to error out only if it found 0 matches. If it found 1 match still pass through

### Why is this needed?

To decrease the need to have conditional steps in the workflow to do file type checks.

**Comment by codezninja** [comment]
Actually looking through the [source](https://github.com/actions/upload-artifact/blob/main/dist/index.js#L4435) it seems like this should be supported but I'm getting an error even though one of the path should exist

**Comment by codezninja** [comment]
For now I've gotten around this but using `[]`

```yaml
      - name: Upload java artifact
        uses: actions/upload-artifact@v3
        with:
          name: java-artifact
          path: |
            ${{ github.workspace }}/target/*.[jw]ar
          if-no-files-found: error
```
