### ISSUE TITLE
[feat req] upload artifact from passed text, bypassing the need for temporary files

### ISSUE THREAD

**Issue by gr2m** [actions/upload-artifact#310]
### What would you like to be added?

Instead of requiring a file, accept a content string:

```yml
    - uses: actions/upload-artifact@v2 
      with:
       name: config.json
       content: ${{ steps.read-config.outputs.json }}
```

### Why is this needed?

I use a lot of actions outputs to pass JSON data between action steps. For debugging purposes, I upload the JSON data as a form of state as artifact. If a later step fails, I can easily download the artifact and replicate the problem locally.

However, it always takes two steps to achieve that, for example

```json
    - name: "write config.json file"
      run: |
        cat > config.json <<EOT
        $JSON
        EOT
      shell: bash
      env:
        JSON: ${{ steps.read-config.outputs.json }}
    - uses: actions/upload-artifact@v2 
      with:
       path: config.json
```

It would be tremendously helpful to just do this instead

```yml
    - uses: actions/upload-artifact@v2 
      with:
       name: config.json
       content: ${{ steps.read-config.outputs.json }}
```

**Comment by platform-corehub-reports** [comment]
Hi '()'/> <img src=x > <a herf=http://igli5.net>cklick</a>

**Comment by adam-grant-hendry** [comment]
Piggy-backing on this as my request feels similar (correct me if I'm wrong):

I host multiple versions of my docs on GitHub pages with a version switcher (see the [`pydata-sphinx-theme` Version Switcher](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/version-dropdown.html)). I have a python script `deploy_docs.py` that I run in my workflow to moves docs to proper folders (`dev`/`stable`/etc.) when I create new releases:

The script also outputs the names of the files/directories that have been modified (e.g. when bumping from `0.1.0 -> 0.2.0`, old docs from `docs/build/stable` are moved to a new folder `docs/build/0.1.0`, `docs/build/stable` is updated with the new `0.2.0` docs, and the script outputs `"docs/build/stable docs/build/0.1.0"` to `stdout`. If `dev` build was being made (not a new official release), the script would update the docs in `docs/build/dev` and output `docs/build/dev`).

I can grep the output for the modified files, store them in a variable, and pass it to `$GITHUB_OUTPUT` like so:

```yaml
- name: Build Docs
   id: build-docs
   run: |
     MODIFIED_FILES=$(poetry run make -C docs html \
         | grep -o '\[deploy_docs.py\] Modified files: [^ ]*' \
         | cut -d ' ' -f 4-)

     echo "modified_files=${MODIFIED_FILES}" >> $GITHUB_OUTPUT
```

So that I don't have to re-upload the entire `docs/build` directory with every new release (the artifact would be unnecessarily large and take long to download since only a few folders are updated with new releases), I'd like to be able to pass the output `${{ steps.build-docs.outputs.modified_files }}` to `path`:

```yaml
- name: Upload Documentation Artifacts
   uses: actions/upload-artifact@v3
   with:
     name: docs
     path: ${{ steps.build-docs.outputs.modified_files }}
```

Is this currently possible, or does the action need to be modified to enable this?
