### ISSUE TITLE
[bug] Uploaded macOS bundle becomes folder

### ISSUE THREAD

**Issue by paulz** [actions/upload-artifact#326]
### What happened?

In our workflow:
```
      - name: Save Xcode archive
        uses: actions/upload-artifact@v3
        with:
          path: App.xcarchive
          name: App.xcarchive
```

### What did you expect to happen?

we expect download name to be `App.xcarchive`

### How can we reproduce it?

on macOS runner 

```
      - run: mkdir App.xcarchive
      - name: Save Xcode archive
        uses: actions/upload-artifact@v3
        with:
          path: App.xcarchive
          name: App.xcarchive
```

On build summary artifact is shown as `App.xcarchive` 
but when we download it we see it as a folder `App`

As a workaround we manually rename `App` folder to `App.xcarchive`  and becomes Xcode archive bundle

### What version of the action are you using?

v3

### What are your runner environments?

self-hosted, macos

**Comment by Lecrapouille** [comment]
Same issue for me :( The reason is that MacOS application bundle is a folder. Probably we have to create the .dmg file

**Comment by Lecrapouille** [comment]
@paulz I fixed with:
```
      - name: Create the DMG file
        run: |
          hdiutil create -format UDZO -srcfolder build/XXX.app build/XXX.dmg
...

      - name: Deploy
        uses: actions/upload-artifact@v3
        with:
          name: XXX-macos
          path: build/XXX.dmg
```

AFAIK since I do not have MacOS I cannot check if the dmg is functional
