### ISSUE TITLE
Artifact is not getting upload if test failed when message shows "Error: Process completed with exit code 1."

### ISSUE THREAD

**Issue by neerajkumarlad** [actions/upload-artifact#328]
### What happened?

Artifact is not getting upload if test failed and message shows "Error: Process completed with exit code 1."

I am trying to upload allure report once webdriverIO automation is completed with pass/fail cases. On Every test case passed, reports gets uploaded but if test failed i could not see the uploaded artifact. 

Here is yaml code:
```
name: Automation using WebDriverIO
on:
  workflow_dispatch:
    branches:
      - workingBranch 
  schedule:
    - cron: "0 8 * * *"
    - cron: "0 18 * * *"

jobs:
  WebdriverIO-Automation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.13.0
      - name: Install
        run: npm install
      - name: Test
        run: npm run stage-test

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Setup allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Upload allure report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
          if-no-files-found: error
          retention-days: 30

```

Here is summary of allure report concole lop:

<img width="1179" alt="image" src="https://user-images.githubusercontent.com/105440014/170930816-672a587f-cb11-45dc-9f42-b03a33e92a16.png">

Here is Github action screen:
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/105440014/170931077-6f3c5482-f359-4549-bfb6-6968a85f1c4a.png">

### What did you expect to happen?

Even test failed with failed report folder, upload artifact should upload the file

### How can we reproduce it?

Create WebDriverIO project
intentionally failed the test case
run the github action ( use above yaml code)

### What version of the action are you using?

2.291.1

### What are your runner environments?

linux
