### ISSUE TITLE
[feat req] Ability to upload multiple artifacts

### ISSUE THREAD

**Issue by mih-kopylov** [actions/upload-artifact#331]
### What would you like to be added?

When building a go application for multiple platforms, I would like to upload the built artifacts as separate files, like this:

* app_darwin_amd64
* app_freebsd_amd64
* app_linux_amd64
* app_windows_amd64.exe

### Why is this needed?

Right now I have to duplicate the following action call for each binary, and that's not convenient at all

```
      - name: Upload built artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app_darwin_amd64
          path: ./app_darwin_amd64
```

**Comment by retorquere** [comment]
Doesn't this work for you?

```
      - name: Upload built artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app_darwin_amd64
          path: |
            ./app_darwin_amd64
            ./app_freebsd_amd64
```
