### ISSUE TITLE
Support Retention Policies

### ISSUE THREAD

**Issue by jahed** [actions/upload-artifact#34]
Now that GitHub has a strict quota and charges on storage usage, the ability to remove artifacts is an essential feature. This is covered in #5, however, since Actions are automated, manual removal is too tedious.

I'd like to suggest supporting retention policies instead where after a period of time (specified in the job step), artifacts automatically clear themselves out to avoid wasting storage space.

For example, when sharing artifacts between jobs, they're only needed for an hour maximum, and for debugging tests they may not be needed for more than a day.

Here is a configuration example where `expires` is the retention policy given in seconds.

```yaml
- uses: actions/upload-artifact@v1
  with:
    name: my-artifact-for-one-hour
    path: path/to/artifact
    expires: 3600
- uses: actions/upload-artifact@v1
  with:
    name: my-artifact-for-one-day
    path: path/to/another/artifact
    expires: 86400
```

Without this, the entire idea of "Shared Storage" in GitHub Actions is unusable for Teams and Individuals with fixed budgets as the costs will just keep growing.

#5 will still be needed to remove artifacts that don't have a retention policy.

**Comment by JCMais** [comment]
+1 here, it is currently not viable to use this action right now.

It will just increase costs indefinitely, even more if you are storing big, short-lived, artifacts.

**Comment by splitt3r** [comment]
The way GitLab CI solves this is pretty nice (https://docs.gitlab.com/ee/ci/yaml/#artifactsexpire_in). That would be a great addition.

**Comment by thomasboyt** [comment]
Also looking for this. My current project I'm adopting happens to be a public one so it's not a big deal, but this would stop me from ever using GH Actions artifacts in a private project.

Considering this is the only way to share state between jobs, an option to delete artifacts after the workflow completes would also be great. This would make it possible to not store artifacts that are only used for sharing state at all.

**Comment by le0m** [comment]
@thomasboyt you can use the [cache action](https://github.com/actions/cache) to share state between jobs during the same workflow as a workaround. That's what we're currently doing, waiting for this issue to be resolved.

**Comment by zbeer** [comment]
+1

**Comment by konradpabjan** [comment]
Thanks for the suggestion @jahed!

Retention policies is something that would be great to have, lots of uses cases for things such as storage quotas.

Nearly identical (keeping both open): https://github.com/actions/upload-artifact/issues/49

An expiration time that is just tied to seconds seems a little limited though. Certain users might want 30 days for example (vs the current 90 default) so having to type 2592000‬ seems pretty ugly and hard to understand if there are no comments. 

I like what GitLab does with their expiration times, (days, hours and even years are supported). There is also this time format that i've come across that is defined [here](https://docs.microsoft.com/en-us/azure/kusto/query/scalar-data-types/timespan#timespan-literals) that uses `d`, `s`, and `m` for things like `days`, `seconds` and `minutes` (brief and easy to understand). 

Combining ideas, about something like this?

30 days
```
- uses: actions/upload-artifact@v2-preview
  with:
    name: my-artifact-for-30-days
    path: artifact/path
    expiration: 30d # '30days' or '30 days' would also work
```
1.5 hours
```
    expiration 1.5h #'1.5hrs', '1.5hours' also works
```

20 minutes
```
    expiration: 20m # '20min' or '20 min' also works
```

90 seconds
```
    expiration: 90s #'90sec' or '90 sec' also works
```

It could also be possible to combine types
```
    expiration: 5d 6h 10m 30s
```
