### ISSUE TITLE
[feat req] Add a limit parameter

### ISSUE THREAD

**Issue by kaleidawave** [actions/upload-artifact#357]
### What would you like to be added?

There should be a limit parameter and if the size of the upload is greater than this the action should fail

```yml
- uses: actions/upload-artifact@v3
  with:
    limit-size: 1mb
```

### Why is this needed?

At the moment you can only create a quota across the user account. This would allow more granular artefact uploads in cases where uploading a large asset is actually an error

It is possible to do this via code but would be better for the action to handle it as it already handles the glob lookup etc.
