### ISSUE TITLE
[bug] When the path is a file without an extension it fails

### ISSUE THREAD

**Issue by timheuer** [actions/upload-artifact#368]
### What happened?

Trying to specify a path but the path is to a file with no extension (Dockerfile)...and this action fails because it thinks it is a directory	

### What did you expect to happen?

It understands it is a valid file and uploads it

### How can we reproduce it?

Create a file with no file extension and specify that as the path.

### What version of the action are you using?

v3

### What are your runner environments?

linux

**Comment by konradpabjan** [comment]
Unable to reproduce so closing this out: https://github.com/konradpabjan/artifact-test/actions/runs/7216554657 and https://github.com/konradpabjan/artifact-test/actions/runs/7216577360 

Here is my workflow file:

```
    - name: Create file
      run: |
        echo hello > file
    
    - name: Upload Artifact v4
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact-v4
        path: file
        retention-days: 1

    - name: Upload Artifact v3
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact-v3
        path: file
        retention-days: 1
```

Both with v3 and the new v4 it appears to be working fine. Tried with both `windows-latest` and `ubuntu-latest` 

Maybe I'm missing something in my steps but everything seems to be working fine 🤔 Please reopen if this is still occurring but please provide some simple reproductive steps
