### ISSUE TITLE
[bug] `upload-artefact` doesn't find files despite the previous step showing that they exist in the indicated folders

### ISSUE THREAD

**Issue by preetmyob** [actions/upload-artifact#376]
### What happened?

Here is the output: https://github.com/PreetSangha/password-generator/actions/runs/3842188040/jobs/6543235744

```
0s
Run actions/upload-artifact@v3
  with:
    if-no-files-found: error
    name: extensions
    path: '/home/runner/work/password-generator/password-generator/output/*'
  
Error: No files were found with the provided path: '/home/runner/work/password-generator/password-generator/output/*'. No artifacts will be uploaded.
```

`zip directories` step:
```
Run mkdir output
  mkdir output
  zip -r output/firefox.xpi firefox
  zip -r output/chrome.crx  chrome
  find /home/runner/work/password-generator/password-generator/output
  shell: /usr/bin/bash -e {0}
  adding: firefox/ (stored 0%)
  adding: firefox/manifest.json (deflated 38%)
  adding: firefox/content.js (deflated 70%)
  adding: firefox/style.css (stored 0%)
  adding: firefox/password.html (deflated 61%)
  adding: chrome/ (stored 0%)
  adding: chrome/manifest.json (deflated 37%)
  adding: chrome/content.js (deflated 70%)
  adding: chrome/style.css (deflated 6%)
  adding: chrome/password.html (deflated 61%)
/home/runner/work/password-generator/password-generator/output
/home/runner/work/password-generator/password-generator/output/firefox.xpi
/home/runner/work/password-generator/password-generator/output/chrome.crx
```

here is the pipeline: https://github.com/PreetSangha/password-generator/blob/package-extensions/.github/workflows/main.yml

```yaml
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Zip directories
        run: |
          mkdir output
          zip -r output/firefox.xpi firefox
          zip -r output/chrome.crx  chrome
          find ${{ github.workspace }}/output
      - name: Upload archives
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error 
          name: extensions
          path: |
            '${{ github.workspace }}/output/*.xpi'
            '${{ github.workspace }}/output/*.crx'
```

### What did you expect to happen?

I would expect it to find the files that have just been created

### How can we reproduce it?

Rerun the actions https://github.com/PreetSangha/password-generator/actions/runs/3842188040/jobs/6543235744

### What version of the action are you using?

3

### What are your runner environments?

linux
