### ISSUE TITLE
[bug] Artifacts are uploaded duplicating root folder

### ISSUE THREAD

**Issue by arthurgeron-work** [actions/upload-artifact#378]
### What happened?

For a project, lets say ProjX in this case, if a file is uploaded it seems that it duplicates the root folder, so when you download it, instead of downloading into ProjX -> ProjX/artifact.log it downloads into ProjX/ProjX/artifact.log

### What did you expect to happen?

Uploaded artifacts should download straight into the root folder unless otherwise instructed.

### How can we reproduce it?

Do a upload in a job, ex:
```
- name: 'Upload Lint Report'
        uses: actions/upload-artifact@v3
        with:
          name: lintReport.json
          path: lintReport.json
          if-no-files-found: warn
          retention-days: 5
```
Then in a next job do the download:
```
- name: Download All Artifacts
        uses: actions/download-artifact@v3
```

Check the logs, it will show something like this:
![Captura de Tela 2023-01-09 às 14 59 50](https://user-images.githubusercontent.com/71399856/211375825-6a4a8a78-c0bb-4810-a0d8-1c418b950d0e.png)

### What version of the action are you using?

v2.6.0

### What are your runner environments?

linux
