### ISSUE TITLE
upload-artifact loses file permissions when zipping the provided path

### ISSUE THREAD

**Issue by krcroft** [actions/upload-artifact#38]
The baseline behavior of the `zip` utilty on Linux and macOS is to retain permissions.

However, when the `upload-artifact` action zips a directory, it loses permissions. With permissions broken and lost in the resulting asset zipfile, this subsequently breaks the artifacts for users or for downstream automated scripts.

**Expected behavior**: the permissions applied to files and directories, a defined and configured by prior steps in the workflow, should not be dropped or ignored by `upload-artifact` and should be present in the resulting asset zip file.

**Comment by krcroft** [comment]
Moving this issue to the `download-artifact` action, as that's where the zipping is performed. Moved to https://github.com/actions/download-artifact/issues/14.

**Comment by nhooyr** [comment]
Can confirm that with `unzip -Z` on the resulting .zip, there are no executable permissions on files that should have executable perms.

**Comment by jrozner** [comment]
Is anything being done about this? It's been over 6 moths and this is the recommended way by GitHub to handle artifact upload

**Comment by adriangb** [comment]
This is still broken as of today, very annoying.

**Comment by bcardiff** [comment]
I am not proud of it, but actions/cache@v2 keeps the permissions. If the goal is to pass some artifacts between jobs the following is working for me so far.

```
      - name: Artifact (with permissions)
        uses: actions/cache@v2
        with:
          path: /path/to/store
          key: artifacts-${{ github.run_id }}-${{ github.run_number }}
```

**Comment by thetroy** [comment]
A workaround is documented in the readme

https://github.com/actions/upload-artifact#maintaining-file-permissions-and-case-sensitive-files
```
  - name: 'Tar files'
    run: tar -cvf my_files.tar /path/to/my/directory

  - name: 'Upload Artifact'
    uses: actions/upload-artifact@v2
    with:
      name: my-artifact
      path: my_files.tar  
```
