### ISSUE TITLE
Upload files in file-only mode or ignore the folders

### ISSUE THREAD

**Issue by Nambers** [actions/upload-artifact#395]
### What would you like to be added?

For example, in the yml code below:
```yml
    - name: upload
      uses: actions/upload-artifact@v3
      with:
        name: linuxSo
        path: |
          ./cpp/build/*.so
          /lib/x86_64-linux-gnu/libcrypt.so.1
```
I want my uploaded folder only contains those libraries themselves instead of containing folders like  `home\runner\work\repo\repo\cpp\build\aaa.so`, like using `zip -j` under Linux.

### Why is this needed?

This feature is not very critical, because developers can manually copy those files into a folder, and then upload the entire folder.
But I think it will be great to have this feature if there are lots of single files in different paths.
