### ISSUE TITLE
[feat req] Support setting compression level

### ISSUE THREAD

**Issue by 8MiYile** [actions/upload-artifact#398]
### What would you like to be added?

want support setting compression level

### Why is this needed?

Because I found a problem in the build
The difference in footprint between two compressions and one compression is half
https://github.com/8Mi-Tech/CefDetectorX/actions/runs/4675681366
https://github.com/8Mi-Tech/CefDetectorX/actions/runs/4662555125

---

https://computingforgeeks.com/highest-zip-compression-level-on-linux/#:~:text=Tthe%20total%20number%20of%20zip%20compression%20levels%20is,suffix%20list%29.%20The%20default%20compression%20level%20is%20-6.

**Comment by 8MiYile** [comment]
old
```yaml
- uses: actions/upload-artifact@v2
  with:
    name: my-artifact
    path: path/to/artifacts/
```

new
```yaml
- uses: actions/upload-artifact@v2
  with:
    name: my-artifact
    path: path/to/artifacts/
    type: zip
    level: -8
```
