### ISSUE TITLE
[bug] Delay in Artifact Being Available for Listing Causes Triggered Workflow Runs to Fail

### ISSUE THREAD

**Issue by mesporas-talis** [actions/upload-artifact#400]
### What happened?

A workflow run tried to find artifacts that were uploaded from the workflow run that triggered it. I followed the steps in this documentation with some modifications to store the run number instead of the PR number: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#using-data-from-the-triggering-workflow

The triggered run resulted in this error:
`Unhandled error: TypeError: Cannot read properties of undefined (reading 'id')`

I saw that the artifact for the initial workflow was not displayed in the UI for some time.

After rerunning the triggered workflow when the artifact was available, then the workflow completes.

### What did you expect to happen?

I expected the artifact to be available for a triggered workflow run that may need it without needing to rerun the job.

### How can we reproduce it?

Following the steps in this documentation will reproduce the issue: 
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#using-data-from-the-triggering-workflow

My modified version of the documentation code is below:

The initial workflow
```
name: Upload data

on:
  workflow_dispatch

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Save Run number
        env:
          RUN_NUMBER: ${{ github.run_number }}
        run: |
          mkdir -p ./run
          echo $RUN_NUMBER > ./run/run_number
      - uses: actions/upload-artifact@v3
        with:
          name: run_number
          path: run/
```

The triggered workflow
```
name: Use the data

on:
  workflow_run:
    workflows: [Upload data]
    types:
      - completed

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: 'Download artifact'
        uses: actions/github-script@v6
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "run_number"
            })[0];
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/run_number.zip`, Buffer.from(download.data));

      - name: 'Unzip artifact'
        run: unzip run_number.zip

      - name: "Echo Run number"
        run:
          cat run_number
```

### Anything else we need to know?

This may be related to https://github.com/actions/upload-artifact/issues/389

### What version of the action are you using?

v3

### What are your runner environments?

linux
