### ISSUE TITLE
[bug] Upload of directory on MacOS extremely slow

### ISSUE THREAD

**Issue by adentinger** [actions/upload-artifact#401]
### What happened?

Action [took nearly 3 hours to complete](https://github.com/adentinger/CMakeBestPractices/actions/runs/4711063227/jobs/8355203404), despite the `Total size of all the files uploaded` being merely `100365 bytes`.

This didn't happen just once; [it seems to happen every time](https://github.com/adentinger/CMakeBestPractices/actions/runs/4714860170/jobs/8361459194).

However, putting the files into an archive (e.g. `.tar.gz`) and uploading that archive [does allow the upload to happen quickly](https://github.com/adentinger/CMakeBestPractices/actions/runs/4716200464/jobs/8363711117).

### What did you expect to happen?

Action should have completed within a few seconds, or at most a minute.

### How can we reproduce it?

```yaml
    - name: Upload assets for release
      uses: actions/upload-artifact@v3
      with:
        name: release-macos-latest
        path: |
          ${{github.workspace}}/repo/prj1/packages/
          ${{github.workspace}}/repo/prj2/packages/
          !**/_CPack_Packages/
```
[Example workflow](https://github.com/adentinger/CMakeBestPractices/blob/39b218ef79a6ffff7563a2d4182478d5e564744c/.github/workflows/cmake.yml#L141)

### Anything else we need to know?

Seems to be the same issue as #163, but because that is two years old and refers to `v2` I decided to create a new issue.

### What version of the action are you using?

v3

### What are your runner environments?

macos
