### ISSUE TITLE
[feat req] Support property for gathering only untracked files

### ISSUE THREAD

**Issue by t-b** [actions/upload-artifact#407]
### What would you like to be added?

If files which will be gathered as artefact can also be part of the repo, it is currently quite fragile to select which ones to collect:

```yaml
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: somename
          path: *.abcd # generated
                !file2.abcd # commited to repo
```

### Why is this needed?

The competition has https://docs.gitlab.com/ee/ci/jobs/job_artifacts.html#with-untracked-files which would make the above example into something like

```yaml
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          untracked: true
          name: somename
```

which is more futureproof and shorter.
