### ISSUE TITLE
[feat req] Expose GlobOptions

### ISSUE THREAD

**Issue by jarruda** [actions/upload-artifact#416]
### What would you like to be added?

Expose [GlobOptions](https://github.com/actions/toolkit/blob/main/packages/glob/src/glob.ts#L16) to the action and use them when globbing files for inclusion into the artifact.

E.g.
```yaml
- uses: actions/upload-artifact@v3
  with:
    name: my-artifact
    path: path/to/artifact/*
    glob-options:
      implicit-descendants: false
```

### Why is this needed?

There is currently no way to non-recursively upload a directory's contents due to the default behavior of the wildcard operator in the glob library.  This behavior includes descendants by default, counter to most glob library behavior (which use the globstar [**] to indicate globbing should be recursive.)

It would also enable other options to be specified which are currently not possible such as following symlinks.
