### ISSUE TITLE
[feat req] Non-zip artifacts

### ISSUE THREAD

**Issue by cnlohr** [actions/upload-artifact#426]
### What would you like to be added?

It may already be possible, but I can't figure out how to do it.  For a variety of reasons, I would find it very useful if we could upload non-zip artifacts.

### Why is this needed?

For instance:

1. It would be possible to upload an image on-commit with information about the specific build that outlines details about the repo's current state.
2. If I want to upload a .zip file, I don't want it double-zipped.
3. Artifacts can be used by embedded devices to update, whereas zipped files are hard to deal with on embedded devices.

**Comment by theogravity** [comment]
This is important for uploading AppImage files on Linux:

https://docs.appimage.org/packaging-guide/distribution.html#do-not-put-appimages-into-other-archives

**Comment by MohabMohie** [comment]
++ same concern for double zipping files
and also if I want to attach log files or html files and easily access them from a mobile device :)

**Comment by plauche** [comment]
++ Would love to see this. I'm using this action to quickly bundle up tooling directories, and since permissions are erased by the action I find myself creating archives of the directories. Which are then zipped up by the action so my users must extract the artifacts twice.

**Comment by flywire** [comment]
Support simply renaming the zip file extension without zipping it again so the artifact can be opened as a document.

Eg: https://en.wikipedia.org/wiki/OpenDocument

> The Open Document Format for Office Applications (ODF), also known as OpenDocument, standardized as ISO 26300, is an [open file format](https://en.wikipedia.org/wiki/Open_file_format) for [word processing](https://en.wikipedia.org/wiki/Word_processor) documents, [spreadsheets](https://en.wikipedia.org/wiki/Spreadsheet), [presentations](https://en.wikipedia.org/wiki/Presentation_program) and graphics and using [ZIP](https://en.wikipedia.org/wiki/Zip_(file_format))-compressed[[6]](https://en.wikipedia.org/wiki/OpenDocument#cite_note-6) [XML](https://en.wikipedia.org/wiki/XML) files.

**Comment by JamesAllsopp** [comment]
This really needs adding. I use a flow to build a pdf from latex. I could view this directly in my browser if it hadn't been zipped.

**Comment by cnlohr** [comment]
For me it is primarily for something very similar, in that it would be very helpful to output a .svg or .png that contains detailed information about the build.

**Comment by c92s** [comment]
+1 from me too, I would like to upload test reports in HTML format, which could then viewed directly in the browser.

**Comment by qaniere** [comment]
+ 1 from me to, would be great to view files from the browser

**Comment by Mitkee** [comment]
In most of my workflows, I have test reports generated in HTML formats. While it's nice that I -can- upload the reports, opening them from a ZIP archive is quite tedious. 

If the concern is for size of uploads here negatively affecting performance, perhaps we could limit non-zipped uploads to be say <= 5Mb in size? Alternatively, could we get some sort of convenience function to just open the unzipped file straight in the browser without having to go through the unzip step?

**Comment by mpeysakhov-PTC** [comment]
Generating a tarpaulin.html coverage report but cannot give direct link to it since it is zipped.

**Comment by lakruzz** [comment]
I a simple use case: building a HTML report from by coverage - like this:

```yaml


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv sync --dev

    - name: Test with pytest
      run: |
        pipenv run pytest --cov=. -m dev

    - name: Generate coverage report
      run: |
        pipenv run coverage html

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: htmlcov/
```

I just want to browse the HTML content of the folder `htmlcov` folder. But what I get is a zip file to download to unzip and browse locally. Not very convenient.

Hosting a HTML report like this is a really nice feature, I've used a similar approach a in both Azure Pipelines and Jenkins - a lot - it's sad that this is (apparently) not possible in GitHub workflows.

...or am I missing something? Is get it that `actions/upload-artifact` can't do this, but is there an alternative way to achieve this.

**Comment by michaelcadilhac** [comment]
> ...or am I missing something? Is get it that `actions/upload-artifact` can't do this, but is there an alternative way to achieve this.

The alternative is to upload the artifact somewhere else, with another mean.  I'm using https://github.com/bxb100/action-upload to upload to a personal server using WebDAV.

**Comment by lakruzz** [comment]
>to upload the artifact somewhere else,

But I really just want this to be part of the run. It has the advantage that is shares the security and access settings on the repo, so I don't have to redo all of that, in a different context. And it also has the advantage that it's part of the natural purge process that runs are deleted after a while, so I also don't have to organise a different cleanup process.

These are features that are available in most other pipeline tools.

**Comment by lakruzz** [comment]
Just wanted to follow up, that we found an acceptable work-around to our concrete problem using `irongut/CodeCoverageSummary"

```yaml


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv sync --dev

    - name: Test with pytest
      run: |
        pipenv run pytest --cov=. -m dev

    - name: Generate coverage report
      run: |
        pipenv run coverage xml -o coverage.xml

    - name: Create Code Coverage Summary
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage.xml
        badge: true
        format: markdown
        output: both
``` 

It generates a cobertura compliant XML report which is then converted to markdown and applied to the action run instance's summary.

Not a browsable HTML report, but good enough.

_Thanks to @ravvnen_ 🙏

**Comment by jameshball** [comment]
+1 This is especially annoying with the release of v4 where now every job is its own artifact. I have several jobs that all produce a single file, and now everything is in separate zips rather than one big zip, or several individual non-zip files.

**Comment by giuliomoro** [comment]
A workaround is to ab-use a dummy release to upload arbitrary files to it. This should do, if you have already created a release out of a dummy tag `dummy-release` and that you have created some artifacts that include the HASH (or other unique ID). 

```
    - name: Upload release assets
      uses: softprops/action-gh-release@v2
      with:
        tag_name: dummy-release
        files: |
          myfile-HASH.deb
          myfile-HASH.txt
```

Variations of this could create a new release per workflow run. None of these is ideal, and they may require some manual cleanup from time to time (especially if expiring artifacts is a feature for you), but they may work in some cases.
