### ISSUE TITLE
[bug] [windows] Upload of files from different drives should work

### ISSUE THREAD

**Issue by koppor** [actions/upload-artifact#431]
### What happened?

I have following upload configuration (minimized)

```yaml
      - uses: actions/upload-artifact@v3
        with:
          path: |
            "*.log"
            miktex-report.txt
            C:\\Users\\runneradmin\\AppData\\Local\\MiKTeX\\miktex\\log
```

When I execute, the action, I get

```
Error: The rootDirectory: D:\a\mwe-miktex\mwe-miktex is not a parent directory of the file: C:\Users\runneradmin\AppData\Local\MiKTeX\miktex\log\initexmf.log
```

This is true, but there should be no error.

### What did you expect to happen?

Artifact created with

- `/d/a/mwe-miktex/mwe-miktex/demo.log`
- `/c/Users/runenradmin/AppData/Local/MiKTeX/miktex/log/initexmf.log`

### How can we reproduce it?

- Commit: [koppor/mwe-miktex@`4745a79` (#24)](https://github.com/koppor/mwe-miktex/pull/24/commits/4745a79d1695f2ef6d5d12b72121f4f49b445fc1)
- Action run: https://github.com/koppor/mwe-miktex/actions/runs/5997142934/job/16262968923?pr=24

### What version of the action are you using?

v3

### What are your runner environments?

window
