### ISSUE TITLE
Exclude files/dirs either by name or regexp

### ISSUE THREAD

**Issue by tysonite** [actions/upload-artifact#44]
It would be nice to have a way to exclude some files/directories from uploading. I would think about something like this:
```
steps:
- uses: actions/checkout@v1

- run: mkdir -p path/to/artifact

- run: echo hello > path/to/artifact/hello.txt
- run: echo hello > path/to/artifact/world.txt

- uses: actions/upload-artifact@v1
  with:
    name: my-artifact
    path: path/to/artifact
    exclude: .*rld.*
```
So only hello.txt will be archived/uploaded.

Might be [ANT syntax](https://ant.apache.org/manual/Types/fileset.html) is good.

**Comment by olegburov** [comment]
Or filter like:

```
steps:
- uses: actions/checkout@v1

- run: mkdir -p path/to/artifact

- run: echo hello > path/to/artifact/A/hello.txt
- run: echo hello > path/to/artifact/A/B/hello.txt
- run: echo hello > path/to/artifact/C/world.txt

- uses: actions/upload-artifact@v1
  with:
    name: my-artifact
    path: path/to/artifact/A/**/*
```

**Comment by solodon4** [comment]
Why not just accept your regular wildcards for paths: one should be able to list multiple wildcards, all files matching them will be included. When the wildcard is negative (starting from !), files matching it will be excluded.

**Comment by eine** [comment]
@solodon4, I included your proposal to use `!`, in https://github.com/actions/upload-artifact/issues/3#issuecomment-524442814

**Comment by solodon4** [comment]
Thank you @eine ! My point was also to have it as unified as possible with other places you guys use path patterns, e.g. path triggers where you can have an array of path patterns, both positive and negative. This will ensure the cognitive burden of learning where what is accepted will be minimized.

**Comment by JesseTG** [comment]
I agree, this would be nice.

**Comment by eng-dibo** [comment]
+1

**Comment by EwoutH** [comment]
Being able to include and exclude certain files using and `*` (wildcards) and `**` (recursive wildcards) would be extremely useful. [AppVeyor supports this](https://www.appveyor.com/docs/packaging-artifacts/#basics).

It's also very useful to search for files like with a certain name, especially if you don't know exactly in which directory they ended up in.

Here's an example of wildcard use in Netflix: https://github.com/Netflix/vmaf/blob/master/appveyor.yml#L59

**Comment by konradpabjan** [comment]
With the `v2-preview`, we have added support for wildcards so you can do basic filtering using `**/*`. You can check that out here: https://github.com/actions/upload-artifact/issues/62

The `@actions/glob` package that is being used internally for `v2-preview` does support exclude patterns out of the box: https://github.com/actions/toolkit/tree/master/packages/glob#exclude-patterns

To fully take advantage of this though, we will have to wait until support for multiple paths gets added since even with the `v2-preview` we only accept a single path: https://github.com/actions/upload-artifact/issues/55

Afterwards it should be possible to do something like this (not 100% sure about the final YAML syntax for multiple paths) :
```
- uses: actions/upload-artifact@v2
  with:
    name: my-artifact
    paths: 'path/to/artifact/A/**/*', '!path/to/Artifact/A/temp/**/*', ''!path/to/Artifact/A/**/*.rdl'
```

**Comment by ax4** [comment]
> With the `v2-preview`, we have added support for wildcards so you can do basic filtering using `**/*`. You can check that out here: #62
> 
> The `@actions/glob` package that is being used internally for `v2-preview` does support exclude patterns out of the box: https://github.com/actions/toolkit/tree/master/packages/glob#exclude-patterns
> 
> To fully take advantage of this though, we will have to wait until support for multiple paths gets added since even with the `v2-preview` we only accept a single path: #55
> 
> Afterwards it should be possible to do something like this (not 100% sure about the final YAML syntax for multiple paths) :
> 
> ```
> - uses: actions/upload-artifact@v2
>   with:
>     name: my-artifact
>     paths: 'path/to/artifact/A/**/*', '!path/to/Artifact/A/temp/**/*', ''!path/to/Artifact/A/**/*.rdl'
> ```

Hi @konradpabjan ! I'm not sure how the final YAML syntax has been so far for multiple glob patterns in `upload-artifact v2-preview` and `upload-artifact-v2`, but I managed to do the following with the current glob pattern calling: 

```
- uses: actions/upload-artifact@v2
  with:
    name: my-artifact
    paths: "path/to/artifact/A/**/*\n!path/to/Artifact/A/temp/**/*\n!path/to/Artifact/A/**/*.rdl"
```

Note that, the glob module does support multiple glob patterns by join-ing patterns with `\n` in their source. And in the YAML file, the way to pass line escaper `\n` is to use double-quote to warp the text (Reference to [strings-in-yaml: to quote or not to quote](http://blogs.perl.org/users/tinita/2018/03/strings-in-yaml---to-quote-or-not-to-quote.html)). 

Also, some links to my test if anyone needs an idea: my testing [workflow file](https://github.com/ax4/upload-artifact-glob-test/blob/master/.github/workflows/upload.yml), [testing commit](https://github.com/ax4/upload-artifact-glob-test/commit/2d038fc2c455f6e96ae6b05d8a144251fd838f59), and [runner result](https://github.com/ax4/upload-artifact-glob-test/actions/runs/120083274).
