### ISSUE TITLE
[bug] upload-artifact ignores files starting with dot

### ISSUE THREAD

**Issue by flbraun** [actions/upload-artifact#447]
### What happened?

I generate a couple of files in my jobs that I upload as an artifact. The files follow the name pattern of `.coverage.<random>`. I upload them with the following step:
```
 - name: Store partial coverage data
   uses: actions/upload-artifact@v3
   with:
     name: coverage-data
     path: ".coverage.*"
     if-no-files-found: error
```
The step's `path` is correct as the logs says:
```
With the provided path, there will be 3 files uploaded
```

In a later job I download the artifacts with the following step:
```
- name: Download partial coverage data
  uses: actions/download-artifact@v3
```
The step logs tell me that its downloading a number of files:
```
Total number of files that will be downloaded: 27
```
However, running `ls -lR` shows that the artifact folder doesn't contain any files:
```
.:
total 4
drwxr-xr-x 2 runner docker 4096 Oct 25 12:17 coverage-data

./coverage-data:
total 0
```
The artifact zip from the workflow's summary page is also empty although it states a size of a couple of megabytes.

You can see all of the described steps in this workflow run:
https://github.com/boxine/bx_django_utils/actions/runs/6640185599

### What did you expect to happen?

Dotfiles are included in the artifact zip and are correctly uploaded by the upload-artifact action.

### How can we reproduce it?

Create an empty repo with a couple of dummy files, e.g. `.foo1`, `.foo2`, etc.
Then upload them with `path: ".foo*"`.

### What version of the action are you using?

v3

### What are your runner environments?

linux

**Comment by paulriversx** [comment]
I'm also experiencing this issue with @v4. While we wait for a fix, you can try renaming the file before uploading it and renaming again after downloaded, in my case i needed the .pnpmrc file:

1. Rename `.pnpmrc` before uploading:

```yaml
- name: Rename .pnpmrc file
  run: mv .pnpmrc pnpmrc
```

2. Explicitly include (or wildcard) the renamed file:

```yaml
- name: Upload artifact
  uses: actions/upload-artifact@v4
  with:
    name: pnpm-config
    path: pnpmrc
    if-no-files-found: error
```

3. After downloading in a later job, rename it back:

```yaml
- name: Download artifact
  uses: actions/download-artifact@v4
  with:
    name: pnpm-config

- name: Rename pnpmrc back to .pnpmrc
  run: mv pnpmrc .pnpmrc
```

This workaround allows the `.pnpmrc` file to be included in the artifact while maintaining its original name for most of the workflow. It's not ideal, but it's a functional temporary solution until the core issue with dotfiles is resolved.
