### ISSUE TITLE
Upload transient artifact

### ISSUE THREAD

**Issue by emilianbold** [actions/upload-artifact#45]
Hello,

Some of my artifacts are transient. They transmit data between jobs but I don't want to keep them.

Ideally, I would like to use `actions/upload-artifact` like this:

```yaml
- name: Upload artifact
  uses: actions/upload-artifact@v2
  with:
    name: myartifact
    path: mypath
    temporary: true
```

The `temporary` (or `transient`) flag would mark the artifact as transient and automatically delete it when the workflow is done.
