### ISSUE TITLE
[bug] if-no-files-found: error doesn't check all files

### ISSUE THREAD

**Issue by nicolalunghi-xlnx** [actions/upload-artifact#457]
### What happened?

if I use the action like this:
```yaml
 - uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          path: |
            first_dir/
            second_dir/
```

no error is emitted if second_dir doesn't exist

### What did you expect to happen?

to get an error if any of the files/dir is missing

### How can we reproduce it?

```yaml
 - run: mkdir first_dir && touch first_dir/file1.txt
 - uses: actions/upload-artifact@v3
      with:
        if-no-files-found: error
        path: |
          first_dir/
          second_dir/
```

### What version of the action are you using?

v3.1.3

### What are your runner environments?

linux

### Are you on GitHub Enterprise Server? If so, what version?

no

**Comment by keeeal** [comment]
This bug is still present in v4.

When specifying more than one file explicitly, e.g.

```yaml
- uses: actions/upload-artifact@v4
  with:
    if-no-files-found: error
    path: |
      file_1.jpg
      file_2.jpg
```

The step fails if `file_1.jpg` and `file_2.jpg` are both missing, but does not fail if just one file is missing.

This is particularly surprising behaviour when listing the files out explicitly like this.
