### ISSUE TITLE
[feat req] change the behavior when providing no name to use the previous name

### ISSUE THREAD

**Issue by wiiznokes** [actions/upload-artifact#463]
### What would you like to be added?

for example, when uploading for example `my-app-1.0.0.deb`, we could use:
```yml
- uses: actions/upload-artifact@v3
  with:
    path: ./my-app-*.deb
```
and the uploaded name will be `my-app-1.0.0.deb` instead of `artifact`.
I think it make more sens and i don't understand why it is not like that.

### Why is this needed?

Because it will be more usefull that `artifact`
