### ISSUE TITLE
[feat req] add option to overwrite existing artifacts

### ISSUE THREAD

**Issue by sni** [actions/upload-artifact#471]
### What would you like to be added?

It would be nice to have a option to allow overwrite existing artifacts like it was possible in v3.

### Why is this needed?

I have an optional workflow step to sign artifacts, it downloads an artifact, signs it and uploads it with the same name again. Worked perfectly fine with `actions/upload-artifact@v3`.
I tried to use `geekyeggo/delete-artifact@v2` but even that doesn't work.
Since this step is not applicable for pull requests, it would make things quite complicated to continue with separate artifact names.

**Comment by robherley** [comment]
👋 If you need to delete an artifact, you can do it with `@actions/github-script`.

Here's a full example:

```yaml
name: Delete Artifact Example
on:
  workflow_dispatch:

permissions:
  actions: write # required permission to delete artifact

jobs:
  upload-and-delete:
    runs-on: ubuntu-latest
    steps:
    - name: Create a File
      run: echo "hello world" > hello.txt
    - name: Upload Artifact
      id: artifact-upload
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: hello.txt
    - name: Delete Artifact
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.actions.deleteArtifact({
            owner: context.repo.owner,
            repo: context.repo.repo,
            artifact_id: ${{ steps.artifact-upload.outputs.artifact-id }}
          });
```

Make sure you have the correct permissions set for the `GITHUB_TOKEN`, as noted above:

```yaml
permissions:
  actions: write
```

I'm not sure if we're going to have an official "overwrite" at this time, since artifacts become _immediately_ available in the public API in v4, unlike in v3 where you had to wait until the end of the run. But thanks for the feedback and I'll bring it up with the team!
