### ISSUE TITLE
[bug] v4 `%` and `#` characters in artifact name causes an Authorization error

### ISSUE THREAD

**Issue by mxcl** [actions/upload-artifact#473]
### What happened?

```
With the provided path, there will be 1 file uploaded
Artifact name is valid!
Root directory input is valid!
Beginning upload of artifact content to blob storage
Error: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:16944f58-601e-00a8-6f73-2fe40e000000
Time:2023-12-15T16:27:52.8549708Z
```

https://github.com/pkgxdev/brewkit/actions/runs/7224478547/job/19686074889?pr=225#step:13:77

### What did you expect to happen?

I've wrapped upload/download in composite actions to make new actions with prior versions. Docs don't say this isn't supported so I was expecting it to continue to work.

### How can we reproduce it?

`my-action/action.yml`:

```yaml
runs:
  using: composite
  steps:
    - uses: actions/upload-artifact@v4
      with:
        path: ${{ steps.tar.outputs.path }}
        name: ${{ steps.tar.outputs.name }}
        if-no-files-found: error
```

### What version of the action are you using?

v4.0.0

### What are your runner environments?

linux

**Comment by robherley** [comment]
👋 hey @mxcl I took a look into this

At first, I was unable to repro your error with a composite action. However taking a closer look, the issue is actually with the _name_ of your artifact:

From [your logs](https://github.com/pkgxdev/brewkit/actions/runs/7224478547/job/19686074889?pr=225#step:13:77): 
```yaml
  with:
    path: /tmp/tmp.6S8Gsh9LWE/stark.com%2Ffoo%3D2.3.4+linux+x86-64.tar
    name: stark.com%2Ffoo%3D2.3.4+linux+x86-64
```

Can you try a name that doesn't have `%` characters in it? I believe there is a bug with encoding the download URL path parameters from the backend storage, I've filed an internal issue.
