### ISSUE TITLE
[bug] (main) using the @main seems to break the pipeline

### ISSUE THREAD

**Issue by vigneshwar221B** [actions/upload-artifact#495]
### What happened?

While running actions/download-artifact@v3, I got the following error when I upload artifacts using the @ main version

> Run actions/download-artifact@v3
Starting download for my-artifact
Error: Unable to find any artifacts for the associated workflow

But when I use the @ v3 version to upload artifacts, everything works

### What did you expect to happen?

To be able to download the uploaded artifacts

### How can we reproduce it?

```yaml
job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/upload-artifact@main
        with:
          name: my-artifact
          path: scripts/test.py
      
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: scripts
```

### Anything else we need to know?

I can see the uploaded artifact in the GitHub repo, so it looks like it's uploaded correctly using @ main. I just can't seem to download it. I know that it's not recommended to use @ main but I'm curious why I'm facing this issue. Thanks.

### What version of the action are you using?

main

### What are your runner environments?

linux
