### ISSUE TITLE
[bug] v4: overwrite: true fails with parallel jobs writing to the artifact 

### ISSUE THREAD

**Issue by yury-s** [actions/upload-artifact#506]
### What happened?

When setting `overwrite: true`, upload sometimes fails with the following output:

```
Run actions/upload-artifact@v4
  with:
    name: pull-request-number
    path: pull_request_number.txt
    overwrite: true
    if-no-files-found: warn
    compression-level: 6
  env:
    FORCE_COLOR: 1
    FLAKINESS_CONNECTION_STRING: 
    ELECTRON_SKIP_BINARY_DOWNLOAD: 1
    PWTEST_BOT_NAME: ubuntu-latest-node18-1
With the provided path, there will be 1 file uploaded
Artifact name is valid!
Root directory input is valid!
Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
```

### What did you expect to happen?

One of the job succeeded and other silently continue doing nothing as documentation of the option suggests.

### How can we reproduce it?

Configure several parallel jobs within a workflow and matrixes to write into the same artifact with `overwrite: true`, something [like this](https://github.com/microsoft/playwright/blob/2d7f456005f4b353f89220e88a039bfb505d5d6b/.github/actions/upload-blob-report/action.yml#L28-L34):

```yaml
    - name: Upload artifact with the pull request number
      if: always() && github.event_name == 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: pull-request-number
        path: pull_request_number.txt
        overwrite: true
```
The upload action will fail sometimes, e.g. see [this run](https://github.com/microsoft/playwright/actions/runs/7641699534/job/20819588957?pr=28932#step:10:63).

### What version of the action are you using?

v4.3.0

### What are your runner environments?

linux, window, macos

**Comment by melloware** [comment]
I get this error as well https://github.com/open-sce/fluent-cli/actions/runs/7254116343/job/19762158254

> Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run

**Comment by darthcloud** [comment]
Updated to v1 as well due to Node.js warning, added overwrite: yes and still getting the error:
https://github.com/darthcloud/BlueRetro/actions/runs/7768402627/workflow

**Comment by melloware** [comment]
I even tried v4.3.0 just to make sure it was using the latest version and the same error happens.

**Comment by melloware** [comment]
I was able to fix my problem by following the migration guide:https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md

See my commit: https://github.com/open-sce/fluent-cli/commit/900fed54e6680276ffbc62365843f005ceb7e990

**Comment by moos3** [comment]
I'm running into the this issue ```Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run``` only on some builds, not always. I'm doing this as the upload 
```
- name: Upload meta bake definition
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.version }}-onbuild-poetry-bake-meta
          path: /tmp/bake-meta.json
          if-no-files-found: error
          overwrite: true
```
Isn't the whole point of overwrite, to overwrite it and not care if that artifact is already there?
