### ISSUE TITLE
List artifacts doesn't work during workflow run

### ISSUE THREAD

**Issue by wchen342** [actions/upload-artifact#53]
I tried to retrieve the list of artifacts in a second job using `GET /repos/:owner/:repo/actions/runs/:run_id/artifacts` after uploading some artifacts by `actions/upload-artifact@v1` in the first job, but the artifacts won't show up. The API call will always return `{ "total_count": 0, "artifacts": [ ] }`.
I have the second job depends on the first job.

Is there a solution to this?

**Comment by KurtGokhan** [comment]
Same for me. I tried to create an action that would delete an artifact created during the run. But artifacts aren't listed until after the run is complete.

**Comment by konradpabjan** [comment]
Both listing an deleting an artifact with the artifacts API only works after a run is complete so the APIs defined in https://developer.github.com/v3/actions/artifacts/ won't work for your scenario. This is largely due to the fact that we don't mark an artifact as `complete` until the end of the run.

To accomplish this, we need some lower level support to list/delete artifacts before the run is complete, see:
https://github.com/actions/toolkit/issues/380
https://github.com/actions/toolkit/issues/379

**Comment by nealkruis** [comment]
This may not be relevant, but is this the same reason artifacts aren't posted on the UI until the entire workflow is complete?

What I don't understand is why artifacts can be downloaded by subsequent jobs, but not by not through other means. Is there a reason not to mark them `complete` after each job?

**Comment by beikov** [comment]
I have the same issue. I'm publishing test failure reports for matrix entries. It's pretty annoying that I can't view the test reports until the workflow is completed. What is the reason for not marking artifacts as complete?

**Comment by CreMindES** [comment]
It's also an issue when you want to launch another workflow (2) that would use an artifact created in the original workflow (1) run, but since (1) is still executing other steps or jobs, the artifact is not available in the API, although it's uploaded already.

**Comment by reuben** [comment]
One /can/ technically just call the same internal APIs used by download-artifact but it's hacky and fragile, and the returned URLs only work with the authorization headers that only exist in the Actions context. It also doesn't give you an artifact ID that will be valid later when the artifacts show up in the REST API. You can see some code that does that here: https://github.com/mozilla/DeepSpeech/blob/a6bdf0ae3c190cbaf39dc4598cc87a55047e38fa/.github/actions/update-cache-index/main.js#L8-L37

I ended up giving up going down that path because I needed stable URLs for the artifacts. It also means that there's a more fundamental change that needs to happen in the way GitHub Actions implements artifacts internally to allow for this issue to be fixed. The internal API being queried is not the GitHub REST API, but rather an Azure Pipelines API, so I'm guessing there's some syncing of state between the two systems that only happens at predetermined times, such as workflow run completion.

**Comment by JacksonKearl** [comment]
It'd be great if this could work better for using [Environments](https://docs.github.com/en/actions/reference/environments) to gate the publishing of a built artifact. We'd like for one stage to build the extension, upload it as an artifact, then a person manually tests the artifact, submits an approving review once they've tested, then the second job comes to publish the same artifact. If we can't access artifacts mid-job, this won't work at all.

**Comment by pauleustice** [comment]
I'm also running into this issue in a release context. We trigger a `repository_dispatch` which creates artifacts (reports etc) for a release and should then upload them in the final job to the release.

Short of uploading the artifacts somewhere for re-use, I don't currently see how we can do this as they must be accessed in a separate workflow as it stands.

**Comment by panayot-cankov** [comment]
@JacksonKearl I was trying to achieve the exact same setup. We are building VS Code extensions that run on MacOS, Windows and Linux. The release workflow is supposed to build a .vsix file in one job, pass it down to few other jobs running e2e tests, and a QA is supposed to manually verify the artefact, if all is ok the team would authorise a publishing environment that would upload the artefact to the store.

I think Actions have some room for improvement for Jobs that include manual labour, as well as the artefacts in those cases should be available somehow before the workflow fully completes.

**Comment by relsqui** [comment]
This is impacting me while writing and testing a new workflow -- I want to verify that the new artifact uploading piece is doing the right thing but I'm not ready to run the whole long workflow yet (and have not yet written the piece that downloads and uses the artifacts).

**Comment by invalidred** [comment]
+1 it makes a tonne of sense to have view artifacts immediately in the workflow and not wait for it to complete. For example we have a rollback step post deploy and our workflow never really ends, however we could have an e2e test fail and would like to view the artifacts even when the workflow is no complete.

**Comment by mm-at-hydro** [comment]
+1. Also have the same requirement to do some manual work before approving to deploy an artifact to an environment. Coming from Azure DevOps, I believe that this functionality was on that platform.

**Comment by robinxb** [comment]
+1 for deploying some artifacts when using other deployment. Now I have to sleep for few seconds to make this work.

**Comment by bradleybertrim** [comment]
Is there any word about this being on the roadmap? I just stumbled upon this limitation yesterday after some head scratching why the list size was 0 after pushing artifacts for a good part of the day. Without this ability we're going to have to scrap the attempt to automate this specific process as it won't be possible without storing the artifacts with a 3rd party.

**Comment by mm-at-hydro** [comment]
There's also this thread in the community:
https://github.community/t/logs-and-artifacts-not-available-in-api-for-in-progress-runs/132091/5 

May be a better place to get eyes on this issue instead of the action "issue" list.

**Comment by kyurkchyan** [comment]
This really really super-duper annoying :( Coming from Azure DevOps this is a must and not acceptable at all.

**Comment by P9155522** [comment]
I also have the same issue . I have a requirement to use  build artifact in release task , which is present currently in a separate job within same dispatch workflow.  How do I achieve this , I am not sure. If anyone has any solution work around . pls Suggest

**Comment by panayot-cankov** [comment]
@P9155522 download and upload artefact actions work between jobs. It is just an UI issue, but the actions can exchange artefacts between jobs. We have a setup where a windows machine would build some VS Cod extension and attach them then Mac Win and Linux will download them and run tests.

**Comment by grasbergerm** [comment]
+1 to this being a huge inconvenience. Coming from CircleCI, this is a reason I'd switch back.

**Comment by rdelmont** [comment]
+1 How are we suppose to make some validation if we cannot access the artifacts before rejecting/approving deployment?

**Comment by panayot-cankov** [comment]
As a workaround, my deployments are making release drafts and attach the artifacts for validation there.

**Comment by marcorighini** [comment]
+1 Is somebody aware if github devs are working on this?

**Comment by deco-dev** [comment]
+1 This is very useful in CircleCI. But actions does not support.

**Comment by acevos01** [comment]
does someone have a solution for this? 😭

**Comment by DamienDennehy** [comment]
This is still an issue 2.5 years later? Oof. I hope this is still being worked on, as we had to switch to AWS S3 to resolve this.

> does someone have a solution for this? 😭

Not a great one. We had to use a third party (S3) for this.

**Uploading**
aws s3 sync ./artifacts s3://bucket_name/folder --delete

**Downloading**
aws s3 sync s3://bucket_name/folder ./artifacts

**Comment by amitsinghsfdc** [comment]
Even after 2 years, the issue is still open and Github has not rolled out this basic feature. This feature is is really needed

**Comment by acevos01** [comment]
> Even after 2 years, the issue is still open and Github has not rolled out this basic feature. This feature is is really needed

I don't think they will change this. Maybe we should close this one. The solution is to a third-party storage as @DamienDennehy mentioned. I'm my case I took Azure Storage and I used a marketplace action [azblob-upload-artifact](https://github.com/marketplace/actions/upload-a-build-artifact-to-azure-blob-storage) to upload the files I needed to my storage container. Good luck

**Comment by cortexcompiler** [comment]
**Disappointed** that GitHub has not solved this yet.  I think a workflow to deploy an artifact that can be used during a CI build to do an initial deploy and re-used to deploy to further environments makes total sense.  To get around this I have had to use an IF statement to use the correct Action based upon the context.  **This works but it painful**:

```
      # Have to use this when the workflow is still in progress due to this issue:
      # https://github.com/actions/upload-artifact/issues/53
      - name: Download artifact (sub-flow)
        uses: actions/download-artifact@v3
        if: github.event_name == 'push'
        with:
          name: ${{ env.ARTIFACT_NAME }}

      - name: Download artifact (dispatch)
        if: github.event_name == 'workflow_dispatch'
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ env.GITHUB_TOKEN }}
          workflow: main-build.yaml
          workflow_conclusion: ""
          name: ${{ env.ARTIFACT_NAME }}
```

**Comment by StuartBow** [comment]
This is a joke that its still not fixed, I'm going back to Azure DevOps

**Comment by DPatrickBoyd** [comment]
+1 to this, just spent the last week building out a pipeline, and the last thing I had to do was delete the artifact from a terraform plan and .terraform folder. Now that it's not working, I feel like it was a waste of my time.

**Comment by DPatrickBoyd** [comment]
I got mad that I this was still a problem, so I just made my own workflow to tackle this. I am using the gh CLI to do the dirty work, but you could use curl or something similar. In my case I am actually deleting the artifact once the workflow that creates it is complete, but it does require to list it first. This may not work for most people since they likely need it during the previous run, but at least this might help someone!

* secrets.GH_REPO_ACCESS_PAT is a PAT that I made and gave it the ability read repos and org stuff as well, not sure how important the scope is.

```
name: Test

on:
  workflow_run:
    branches: [main]
    workflows: [nonprod,prod,test]
    types:
      - completed
jobs:
  on-success:
    runs-on: ubuntu-latest
    name: Delete artifact
    if: github.event.workflow_run.head_branch == 'main' # feel free to take this out if you don't need it
    steps:
      - id: get-id
        run: | # grab the id of the artifact we just created
          echo "ARTIFACT_ID=$(gh api -H 'Accept: application/vnd.github+json'   ${{github.event.workflow_run.artifacts_url}} --jq .artifacts[].id)" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GH_REPO_ACCESS_PAT }}
      - run: |
          echo "artifact id is ${{ env.ARTIFACT_ID}}"
          echo "run url is ${{github.event.workflow_run.artifacts_url}}"
      - id: delete-artifact
        run: | # https://docs.github.com/en/rest/actions/artifacts?apiVersion=2022-11-28#delete-an-artifact
          gh api --method DELETE -H 'Accept: application/vnd.github+json' /repos/${{github.repository}}/actions/artifacts/${{env.ARTIFACT_ID}}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_REPO_ACCESS_PAT }}
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
```
