### ISSUE TITLE
[bug] v4: Duplicate artifacts after FinalizeArtifact timeout

### ISSUE THREAD

**Issue by jbroadus** [actions/upload-artifact#531]
### What happened?

Using a self-hosted runner, uploading a fairly large artifact (5G in this case), I occasionally see this:
```
Finalizing artifact upload
Attempt 1 of 5 failed with error: Request timeout: /twirp/github.actions.results.api.v1.ArtifactService/FinalizeArtifact. Retrying request in 3000 ms...
```
This results in two identical artifact archives.

### What did you expect to happen?

When this error does not occur, a single artifact archive is posted.

### How can we reproduce it?

I haven't created a repro case, but I imagine interrupting the network connection of a self-hosted runner during the finalize would do it.

### Anything else we need to know?

My yaml:
```yaml
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.machine }}-${{ github.run_id }}
          path: "${{ steps.gather.outputs.artifacts }}/*"
          overwrite: true
```

### What version of the action are you using?

v4.3.1

### What are your runner environments?

self-hosted
