### ISSUE TITLE
Delete Artifact Action

### ISSUE THREAD

**Issue by Kamysek** [actions/upload-artifact#550]
### What would you like to be added?

Hello,

Could GitHub consider adding an official "Delete Artifact" action? This would complement the existing upload and download actions, streamlining artifact management in actions. It seems like a natural and beneficial enhancement to the platform. 

Thank you for considering,
Josef

### Why is this needed?

The v4 upload action's inability to append to an existing artifact across various jobs in a matrix complicates artifact management significantly. Users now find themselves in a convoluted cycle of uploading individual outputs as distinct artifacts, downloading these for merging, and re-uploading the merged file for a consolidated outcome. Since then the non consolidated outcome is not needed it would be nice to be able to delete it.

**Comment by robherley** [comment]
> Since then the non consolidated outcome is not needed it would be nice to be able to delete it.

[`actions/upload-artifact/merge@v4`](https://github.com/actions/upload-artifact/tree/main/merge) has a `delete-merged` option, see this example: https://github.com/actions/upload-artifact/tree/main/merge#deleting-artifacts-after-merge

Unfortunately I don't think we'll be investing in a separate delete artifact action anytime soon.

Here's an example of using [github-script](https://github.com/actions/github-script):

```yaml
name: Delete Artifact Example
on:
  workflow_dispatch:

permissions:
  actions: write # required permission to delete artifact

jobs:
  upload-and-delete:
    runs-on: ubuntu-latest
    steps:
    - name: Create a File
      run: echo "hello world" > hello.txt
    - name: Upload Artifact
      id: artifact-upload
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: hello.txt
    - name: Delete Artifact
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.actions.deleteArtifact({
            owner: context.repo.owner,
            repo: context.repo.repo,
            artifact_id: ${{ steps.artifact-upload.outputs.artifact-id }}
          });
    - name: Upload Artifact (again)
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: hello.txt
```

If you find a need to delete artifacts often, you can wrap the code in a composite action, reusable workflow, etc
