### ISSUE TITLE
[bug] all artifacts are not getting uploaded.

### ISSUE THREAD

**Issue by aviralpostman** [actions/upload-artifact#575]
### What happened?

I'm trying to upload multiple files as artifacts, but the generated zip only contains a single file.
![image](https://github.com/actions/upload-artifact/assets/121846649/46bf1219-1ac3-4729-9ee0-bd41bb7162e6)

### What did you expect to happen?

both the files should have been there in the zip file.

### How can we reproduce it?

```
- name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: abc
          path: |
            file1.txt
            file2.txt
```
Upload any 2 files

### What version of the action are you using?

v4

### What are your runner environments?

linux
