### ISSUE TITLE
[bug] Only contents of macOS-Application (***.app) get uploaded

### ISSUE THREAD

**Issue by maxfornacon** [actions/upload-artifact#581]
### What happened?

I tried uploading a macOS-Application (***.app). Instead the contents of the file get uploaded. When I download the artifact I only receive a directory, called "Contents" which typically resides directly inside the app package.

I guess it handles it like a directory, which it technically is, but still kind of an exception.

### What did you expect to happen?

I expected the whole app package to be uploaded, not just the contents.

### How can we reproduce it?

```
      - name: Upload .app as artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-bin-files
          path: ${{ env.MACOS_APP_RELEASE_PATH }}/***.app
          retention-days: 1
```

### What version of the action are you using?

v4.3.3

### What are your runner environments?

macos
