### ISSUE TITLE
[bug] Specifying a symbolic link in the `file` parameter will not upload the target file anymore

### ISSUE THREAD

**Issue by anddani** [actions/upload-artifact#589]
### What happened?

We are using `upload-artifact` to upload the result of a build step which yields a symbolic link to the actual output.

After updating to 4.3.5, our uploaded artifacts were only a handful of bytes even though the generated files are in megabytes. After downgrading to 4.3.4 it started working again.

### What did you expect to happen?

We expect that when referring to a symbolic link, it should upload the file it points to, not the link itself.

### How can we reproduce it?

Here is a repository to show how to reproduce this issue: https://github.com/anddani/upload-artifact-bug-repro/

Here is an example run: https://github.com/anddani/upload-artifact-bug-repro/actions/runs/10218539161

```yml
on:
  workflow_dispatch:

jobs:
  upload-artifact:
    name: Uploading file through symbolic link
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Write file
        run: |
          echo "My file" > file.txt
          ln -s file.txt symbolic-link.txt

      - name: Upload file 4.3.4
        uses: actions/upload-artifact@v4.3.4
        with:
          name: file-4-3-4.txt
          path: ./symbolic-link.txt

      - name: Upload file 4.3.5
        uses: actions/upload-artifact@v4.3.5
        with:
          name: file-4-3-5.txt
          path: ./symbolic-link.txt
```

### What version of the action are you using?

v4.3.5

### What are your runner environments?

linux
