### ISSUE TITLE
Artifacts exceeded limits

### ISSUE THREAD

**Issue by craig-dae** [actions/upload-artifact#59]
We just started getting `Cannot upload artifacts. You may have exceeded your spending limit for storing artifacts with Actions or Packages.`

We have an artifact that takes about 5 minutes to produce, which is fed into a job that spins up multiple containers than run in parallel. The artifacts are only needed to feed these boxes, and can be removed after. 

After 1 day, we started getting the message I wrote above. I have deleted every artifact I could find manually. Then I ran this action here that says it purged all my artifacts: https://github.com/kolpav/purge-artifacts-action

Clicking through as many previous workflows as I could, I found no examples of existing artifacts. 

I continue to the get above message, and all merging has stopped on our project. 

I need to know how to manage my artifacts so this doesn't happen again, and get my pipeline back up asap. 

Thanks!

**Comment by MJomaa** [comment]
Same here

**Comment by yacaovsnc** [comment]
Is this still an issue?

**Comment by craig-dae** [comment]
@yacaovsnc Thanks for getting back to me. I solved this by using `kolpav/purge-artifacts-action@v1`

```
      - name: Clear artifacts
        uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 1hr
```

This seems to keep my artifacts in check. Has this issue been fixed? Can I remove `kolpav/purge-artifacts-action@v1` or do I need to keep it in?
