### ISSUE TITLE
Upcoming breaking change: Hidden Files will be excluded by default

### ISSUE THREAD

**Issue by joshmgross** [actions/upload-artifact#602]
> From September 2nd, 2024, we will no longer include hidden files and folders as part of the default upload of the v3 and v4 upload-artifact actions. This reduces the risk that credentials are accidentally uploaded into artifacts. Customers who need to continue to upload these files can use a new option, ‘include-hidden-files’, to continue to do so.

https://github.blog/changelog/2024-08-19-notice-of-upcoming-deprecations-and-breaking-changes-in-github-actions-runners/

- https://github.com/actions/upload-artifact/pull/598
- https://github.com/actions/upload-artifact/pull/604

**Comment by dolfinus** [comment]
Why introducing breaking changes to v3 and v4 instead of making a new v5 version?

**Comment by uerkut** [comment]
```yaml
      - name: Upload Docker Compose Files Artifact
        id: upload_docker_compose_files
        uses: actions/upload-artifact@v4.4.0
        include-hidden-files: true
        with:
          name: docker-compose-files
          path: |
            .env
            docker-compose.yaml
```

I've edited my workflow like above and getting the error:

`The workflow is not valid. In .github/workflows/kondukto-package-build-manual.yml (Line: 318, Col: 11): Error from called workflow kondukto-io/kondukto-build/.github/workflows/docker_compose_package.yml@c343cea5db32d5d329cfe25ea5f7f84a88ecb64a (Line: 38, Col: 9): Unexpected value 'include-hidden-files'`

I tried both versions `v4` and `v4.4.0`

**Comment by dolfinus** [comment]
> I've edited my workflow like above and getting the error:

You should place `include-hidden-files: true` under `with:` block

**Comment by uerkut** [comment]
Thanks a lot. My bad.

**Comment by buckett** [comment]
This change resulted in deployment failures for us because we no longer included the full set of files in our deployment artifact.

**Comment by Drowze** [comment]
This also resulted in CI failures for us... Would be nice if there was at least a warning before rolling breaking changes 🤷‍♂️ 

Here's how we're calling this action:
```yaml
    - uses: actions/upload-artifact@v4
      with:
        name: artifacts-${{ strategy.job-index }}
        path: |-
          coverage/.resultset.json
          tests/junit.xml
```
