### ISSUE TITLE
[bug]Directory upload fails

### ISSUE THREAD

**Issue by KyoheiG3** [actions/upload-artifact#611]
### What happened?

Starting from v4.4.0, directory uploads will fail.
Even if you specify a `.reg` directory in path, it seems to be mistaken for `.reg.`
Below is the action log.

```
Run actions/upload-artifact@v4
  with:
    name: reg-430
    path: .reg
    if-no-files-found: warn
    compression-level: 6
    overwrite: false
    include-hidden-files: false
  env:
    KEY_STORE_PASSWORD: ***
    PNPM_HOME: /home/runner/setup-pnpm/node_modules/.bin
    STORE_PATH: /home/runner/setup-pnpm/node_modules/.bin/store/v3
Warning: No files were found with the provided path: .reg. No artifacts will be uploaded.
```

### What did you expect to happen?

Be able to upload. In v4.3.6 it was possible.
```
Run actions/upload-artifact@v4.3.6
  with:
    name: reg-430
    path: .reg
    if-no-files-found: warn
    compression-level: 6
    overwrite: false
  env:
    KEY_STORE_PASSWORD: ***
    PNPM_HOME: /home/runner/setup-pnpm/node_modules/.bin
    STORE_PATH: /home/runner/setup-pnpm/node_modules/.bin/store/v3
With the provided path, there will be 772 files uploaded
Artifact name is valid!
Root directory input is valid!
```

### How can we reproduce it?

Specify a directory with no hierarchy in path. Maybe it's due to a hidden folder.

### What version of the action are you using?

v4.4.0

### What are your runner environments?

linux
