### ISSUE TITLE
[feat req] Option to persist zipped artifact to disk post-upload for reuse within the same workflow

### ISSUE THREAD

**Issue by indy-singh** [actions/upload-artifact#622]
### What would you like to be added?

```yaml
persist-zip-to-disk: true (defaults to false)
```

### Why is this needed?

We have a bunch of workflows that have to upload the zipped assets to S3 after we do `actions/upload-artifact@v4`. GH storage is for short term, S3 being for long term storage.

It would be great if we did not have to do this:-

```yaml
    - name: Upload artifacts
      id: artifact-upload-step
      uses: actions/upload-artifact@v4
      with:
        name: ${{github.run_id}}
        path: .\publish
        retention-days: 2
        if-no-files-found: error

    - name: Create zip
      run: Compress-Archive -Path .\publish\* -DestinationPath publish.zip;

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: REDACTED
        aws-region: REDACTED

    - name: Upload zip to S3
      run: aws s3 cp publish.zip s3://REDACTED/example-dotnet-lambda/${{github.run_id}}.zip
```

But something like this instead:-

```yaml
    - name: Upload artifacts
      id: artifact-upload-step
      uses: actions/upload-artifact@v4
      with:
        name: ${{github.run_id}}
        path: .\publish
        retention-days: 2
        if-no-files-found: error
        persist-zip-to-disk: true

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: REDACTED
        aws-region: REDACTED

    - name: Upload zip to S3
      run: aws s3 cp ${{ steps.artifact-upload-step.outputs.artifact-disk-location }} s3://REDACTED/REDACTED/${{github.run_id}}.zip
```

I did have a quick fish around the source, and it looks like the zipping operation is all kept [in memory](https://github.com/actions/toolkit/blob/main/packages/artifact/src/internal/upload/zip.ts).

Obviously, I could _just_ redownload the artefact but that feels wasteful as the zipped stream was just disposed of.

Cheers,
Indy
