### ISSUE TITLE
Actions artifact upload stalls when using self hosted runners

### ISSUE THREAD

**Issue by shaik2419** [actions/upload-artifact#623]
### What happened?

When uploading artifacts using self hosted runners, artifacts gets stalled with below error

```
With the provided path, there will be 550127 files uploaded
Artifact name is valid!
Root directory input is valid!
Beginning upload of artifact content to blob storage
/home/runner/_work/_actions/actions/upload-artifact/v4/dist/upload/index.js:3312
                    throw new Error('Upload progress stalled.');
                    ^

Error: Upload progress stalled.
    at Timeout._onTimeout (/home/runner/_work/_actions/actions/upload-artifact/v4/dist/upload/index.js:3312:27)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)

Node.js v[20](https://github.com/CBRE-GCSO/gcso-iam-eadc/actions/runs/11113819006/job/30878983707#step:10:21).13.1
```

### What did you expect to happen?

Artifacts are uploaded in less than a minute

### How can we reproduce it?

I am running self hosted action runner using the image below. Upload an artifact with 500000 files which in total size is less than 100MB. It times out with the above error. 

`image: actions-runner:2.319.1`

Run the same in ubuntu managed runner, it works

### What version of the action are you using?

2.319.1

### What are your runner environments?

self-hosted, linux

**Comment by yacaovsnc** [comment]
Please let us know if this is still occurring, and if it still does, could you please try with `ACTIONS_ARTIFACT_UPLOAD_CONCURRENCY` env and see if setting it to `10` helps? e.g.:

```
        - uses: actions/upload-artifact@v4
          with:
            name: my-artifact
            path: artifact-path/*
          env:
            ACTIONS_ARTIFACT_UPLOAD_CONCURRENCY: 10
```
