### ISSUE TITLE
[bug] actions/upload-artifact@v4 often fails, but can succeed after trying again

### ISSUE THREAD

**Issue by panbingkun** [actions/upload-artifact#642]
### What happened?

In spark, we often find that `actions/upload-artifact@v4` fails, but after trying again, it will basically succeed. Do we have any `parameters` or `approaches` to avoid this situation? Because the first step in the job may take a long time to execute, and retry is for the entire job, which wastes resources and time.

https://github.com/panbingkun/spark/actions/runs/11733712912/job/32688556735
<img width="1006" alt="image" src="https://github.com/user-attachments/assets/1cb00b92-a195-487c-9e34-aeaa7a7f1c6c">

### What did you expect to happen?

Automatic retry or approaches that can increase the probability of success.

### How can we reproduce it?

Occasionally, it occurs, but recently the probability of it happening is very high. I personally have encountered it once every 2-3 days.

### What version of the action are you using?

v4

### What are your runner environments?

linux

**Comment by yacaovsnc** [comment]
Please let us know if this is still occurring, and if it still does, could you please try with `ACTIONS_ARTIFACT_UPLOAD_CONCURRENCY` env and see if setting it to `10` helps? e.g.:

```
        - uses: actions/upload-artifact@v4.6.0
          with:
            name: my-artifact
            path: artifact-path/*
          env:
            ACTIONS_ARTIFACT_UPLOAD_CONCURRENCY: 10
```
