### ISSUE TITLE
[bug] A name with 2 dashes causes path to be ignored.

### ISSUE THREAD

**Issue by mandrachek** [actions/upload-artifact#648]
### What happened?

I encountered a situation where multiple dashes in the name appear to cause the path parameter to be ignored.

```yml
- name: Upload Build Outputs
  uses: actions/upload-artifact@v4
  if: always()
  with:
     name: release-bundle-outputs
     path: app/build/outputs/
     overwrite: true
```

uploads a zip file with the entire workspace, e.g., `.`, which when downloaded includes `app/build/outputs`, but _everything_ else as well.  Changing the name to `appBundle-outputs` resolves the issue and the zip file contains just the `app/build/outputs` cotntent.

### What did you expect to happen?

The uploaded zip file to only contain the content at the specified path.

### How can we reproduce it?

Do an upload of a sub-directory path with "release-apk-outputs" or "release-bundle-outputs" as the name.

### What version of the action are you using?

4.4.3

### What are your runner environments?

self-hosted, linux

### Are you on GitHub Enterprise Server? If so, what version?

NO
