### ISSUE TITLE
Upload artifact inside container

### ISSUE THREAD

**Issue by caoli5288** [actions/upload-artifact#65]
```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    container: openwrtorg/sdk
    steps:
    - run: |
        cd /home/build/openwrt
        ./scripts/feeds update
        ./scripts/feeds install -a
        make
        sudo cp -a bin/ $HOME
    - uses: actions/upload-artifact@v1.0.0
      with:
        name: packages
        path: bin
```

Got `Path does not exist /home/runner/work/openwrt_sdk/openwrt_sdk/bin`. What path should I use?
