### ISSUE TITLE
[bug] Error: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by StephenHodgson** [actions/upload-artifact#653]
### What happened?

Getting the following error when uploading artifacts
```
Error: Maximum call stack size exceeded
```

### What did you expect to happen?

no error when uploading artifacts

### How can we reproduce it?

seems to be on all actions with uploads as far as I can tell for all my projects across multiple repos

### Anything else we need to know?

Download action repository 'actions/upload-artifact@v4' (SHA:b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882)

```yaml
Run actions/upload-artifact@v4
  with:
    compression-level: 0
    retention-days: 1
    name: ***-windows-Android-Artifacts
    path: c:\runner\_work\***\***/**/*.log
  c:\runner\_work\***\***/Builds/Android/**/*.obb
  c:\runner\_work\***\***/Builds/Android/**/*.apk
  c:\runner\_work\***\***/Builds/Android/**/*.abb
  c:\runner\_work\***\***/Builds/Android/Bundles/
  
    if-no-files-found: warn
    overwrite: false
    include-hidden-files: false
  env:
    IS_RELEASE: ***
    VERSION: ***
    SPLIT_APK:  ***
    BUILD_ARGS:   ***
    RELEASE_CHANNEL: ALPHA
    UNITY_EDITOR_PATH: ***
    UNITY_PROJECT_PATH: ***
    SYMBOLS:  ***
    UNITY_HUB_PATH: ***
    UNITY_EDITORS: ***
    CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE: ***
    GOOGLE_APPLICATION_CREDENTIALS: ***
    CLOUDSDK_CORE_PROJECT: ***
    CLOUDSDK_PROJECT: ***
    GCLOUD_PROJECT: ***
    GCP_PROJECT: ***
    GOOGLE_CLOUD_PROJECT: ***
    CLOUDSDK_METRICS_ENVIRONMENT: ***
    CLOUDSDK_METRICS_ENVIRONMENT_VERSION: ***
Error: Maximum call stack size exceeded
```

### What version of the action are you using?

v4 @ b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882

### What are your runner environments?

self-hosted, window
