### ISSUE TITLE
[bug] hidden files are removed from zip file regardless of include-hidden-files flag

### ISSUE THREAD

**Issue by MattPress** [actions/upload-artifact#657]
### What happened?

We are compressing a .net azure function using `Compress-Archive` and then using `actions/upload-artifact@v4` to upload the resulting .zip. 

After finding the breaking change relating to azure functions and the introduction of `include-hidden-files` I set the flag to true but it is not working. 

Using Compress-Archive locally on the publish directory i can see the `.azurefunctions` directory in the resulting zip once i expand it so im pretty certain the `.azurefunctions` directory is in the .zip which is being uploaded. When i download and view the resulting artifact after the `upload_zip_artifact` step, the directory does not exist.

```
- name: Zip Published Project
          id: zip_project
          shell: pwsh
          run: Compress-Archive -Path "~/binaries/*" -DestinationPath "${{ inputs.artifact-name }}.zip" -Force

- name: Upload Project Artifact
          id: upload_zip_artifact
          uses: actions/upload-artifact@v4
          with:
              name: ${{ inputs.artifact-name }}
              path: ${{ inputs.artifact-name }}.zip
              if-no-files-found: error
              include-hidden-files: true
```

### What did you expect to happen?

I would expect the `actions/upload-artifact@v4` to not impact the contents of a compressed file or adhere to the ` include-hidden-files` flag.

### How can we reproduce it?

Publishing a dotnet-isolated azure function and then using the steps above to compress the publish folder contents then using `actions/upload-artifact@v4` to upload the artifact.

### What version of the action are you using?

v4

### What are your runner environments?

linux
