### ISSUE TITLE
[bug] actions/upload-artifact/merge@v4: when files have the same name, the older one prevails

### ISSUE THREAD

**Issue by marcodicro-dp** [actions/upload-artifact#658]
### What happened?

1) I have this upload-artifact steps in a matrix:
```      
      - name: Upload xUnit report artifact
        if: ${{ !cancelled() }} # Upload artifact regardless of failures
        uses: actions/upload-artifact@v4
        with:
          name: shard-${{ matrix.shard }}-${{ github.run_id }}-test-results
          path: 'test/*_test_results.xml'
 ```

2) And then I have this merge artifacts step:

```
      - name: Merge test results
        uses: actions/upload-artifact/merge@v4
        with:
          name: ${{ github.run_id }}-test-results
          pattern: '*${{ github.run_id }}-test-results'
          delete-merged: true
  ```
  
The issue happens in a re-run failed case. E.g. shard 1 and 2 failed in the first attempt, but they pass on re-run.

1) New shard artifacts are generated
2) Then the merge finds the following artifacts:
   - 123456-tests-results -> contains: 1_test_results.xml (with failure), 2_test_results.xml (with failure), 3_test_results.xml
   - shard-1-123456-test-results -> contains 1_test_results.xml (tests passed)
   - shard-2-123456-test-results -> contains 2_test_results.xml (tests passed)

Resulting merged artifact is:
123456-tests-results -> contains: 1_test_results.xml (with failure), 2_test_results.xml (with failure), 3_test_results.xml-> **Same as before the merge**

  
  

### What did you expect to happen?

We expected the newer files from shard-1-123456-test-results and shard-2-123456-test-results to be chosen instead. With the passing tests results.

### How can we reproduce it?

As stated above

### What version of the action are you using?

v4.5.0

### What are your runner environments?

linux

### Are you on GitHub Enterprise Server? If so, what version?

No
