### ISSUE TITLE
[docs] It is not clear how using the same `name` and `overwrite: true` works between workflows

### ISSUE THREAD

**Issue by piedrahitapablo** [actions/upload-artifact#668]
### What files would you like to change?

We recently migrated some repos from v3 artifact actions to v4, and everything worked, but from time to time, we started seeing some time-outs while trying to download artifacts using `actions/download-artifact@v4`. After trying many things, the definitive solution appears to be adding `overwrite: true`. I wondered how that `overwrite: true` works if two workflows run simultaneously using the same artifact name. I tried reading the README and the [Actions Artifacts](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/storing-and-sharing-data-from-a-workflow) docs but didn't find any mention to this, so I'm asking here:

- Are the workflows going to collide and overwrite each other?
- Is it better to use a unique name per workflow? say `name: build-${{ github.run_id }}`?

For context, here's the upload code:
```yaml
      - name: Save build folder
        uses: actions/upload-artifact@v4
        with:
          name: build
          if-no-files-found: error
          path: build.tar.gz
          retention-days: 1
          overwrite: true
```

and the download code:
```yaml
      - name: Download the build folders
        uses: actions/download-artifact@v4
        with:
          name: build
```

Any help would be appreciated, thanks in advance!

### What are your suggested changes?

Clarify the behavior of `overwrite: true` between workflows
