### ISSUE TITLE
[bug] Artifacts are not expiring

### ISSUE THREAD

**Issue by CDTR-MattConroy** [actions/upload-artifact#670]
### What happened?

1 of 2 artifacts did not expire properly. 
This below workflow completed yesterday, and has correctly expired artifact `themes-deploy`, but not `release-deploy`. Both are set to a `retention-days` of 1 and have been working correctly until recently.
![Image](https://github.com/user-attachments/assets/da28b71f-776e-4d0c-b7ca-3fb99dbb5647)

See also, the following snippets to upload artifacts from 2 different jobs in the same workflow:
```
      - name: Upload artifacts to GitHub
        uses: actions/upload-artifact@v4.3.1
        with:
          name: themes-deploy
          path: .deploy/**/*.zip
          if-no-files-found: error
          retention-days: 1
```

```
      - name: Upload artifacts to GitHub
        uses: actions/upload-artifact@v4.3.1
        with:
          name: release-deploy
          path: .deploy/*.zip
          if-no-files-found: error
          retention-days: 1
```

### What did you expect to happen?

Uploading an artifact with `retention-days` set should expire the artifact after the set time.

### How can we reproduce it?

Presumably creating a job with the same snippets, but as they are practically identical, exact repro step are unknown

### What version of the action are you using?

v4.3.1

### What are your runner environments?

self-hosted
