### ISSUE TITLE
[bug] can't using V4 Gitea didn't throw any of error

### ISSUE THREAD

**Issue by anothaiyoyo** [actions/upload-artifact#672]
### What happened?

Hi everyone .

I usually use actions/upload-artifact@v3 for build the projects it's success without any error for now my project have more files from 483 files to 503 files it's failed and I got error
"Upload finished. There were 18 items that failed to upload
The raw size of all the files that were specified for upload is 2451583384 bytes
The size of all the files that were uploaded is 817267741 bytes. This takes into account any gzip compression used to reduce the upload size, time and storage
Note: The size of downloaded zips can differ significantly from the reported size. For more information see: https://github.com/actions/upload-artifact#zipped-artifact-downloads
::error::An error was encountered when uploading "Projectname" There were 18 items that failed to upload."

So for now I trying to change the version from 3 to 4 but it seems like to skip to upload without any error I'm using Gitea & Gitea Action

and this is my gitea-action.yml

```
      - name: :hammer_and_wrench: Build Gameplay
        uses: game-ci/unity-builder@v4.2.2
        id: build-level-gameplay
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_USERNAME }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          customParameters: "-compressWithLz4HC"
          buildName: Projectname
          targetPlatform: ${{ matrix.targetPlatform }}
          versioning: None
          buildsPath: Gameplay
          dockerMemoryLimit: 80g
          allowDirtyBuild: true

      - name: :package: Post-process Build
        run: |
            # Move directory for easier organization.
            mv Gameplay/${{ matrix.targetPlatform }} Gameplay/projectname_${{ matrix.targetPlatform }}_${{ steps.get-version.outputs.version }}
            echo "Moved build files from Gameplay/${{ matrix.targetPlatform }} to Gameplay/LnF_${{ matrix.targetPlatform }}_${{ steps.get-version.outputs.version }}."

      - name: :outbox_tray: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: projectname_${{ matrix.targetPlatform }}_${{ steps.get-version.outputs.version }}
          path: Gameplay
          overwrite: true
          if-no-files-found: error
```
I should run it seems like it skip failed the error underneath didn't tell anything also .

![Image](https://github.com/user-attachments/assets/4845dbaf-2859-498c-bed4-304ceb316a0e)

### What did you expect to happen?

I should be upload also if it's failed I think it's has some error shown but it's took only 3 second then failed 

### How can we reproduce it?

https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md#migration

trying to do in this docs , didn't success , restart Gitea - gitea action didn't work 

### What version of the action are you using?

v4

### What are your runner environments?

self-hosted

### Are you on GitHub Enterprise Server? If so, what version?

no
