### ISSUE TITLE
.tar.gz

### ISSUE THREAD

**Issue by kousu** [actions/upload-artifact#68]
I am producing a folder of executables in my workflow:

```
      uses: actions/upload-artifact@v1.0.0
      with:
        name: apps
        path: fakeroot/bin/
```

but they are losing their +x bits because they are being archived to a .zip instead of a .tar.gz. Is there a way to make a .tar.gz instead?

It seems like this was partially addressed in `v2-preview` @ https://github.com/actions/upload-artifact/issues/3#issuecomment-598820814 but I still need to double-archive my output to get an accurate output.
