### ISSUE TITLE
[bug] path doesn't take variables into account

### ISSUE THREAD

**Issue by SetTrend** [actions/upload-artifact#680]
### What happened?

I'm trying to upload a .NET project artifact. The artifact is stored at `$GITHUB_WORKSPACE/ProjectName/bin/Release/net9.0-windows/`

But `actions/puload-artifact@4` doesn't seem to resolve the variable I used to address this directory:

![Image](https://github.com/user-attachments/assets/b72ad4aa-3ad8-496d-b7b1-7f14f1bfda20)

### What did you expect to happen?

I'd expect `actions/puload-artifact@4` to resolve both, variables and relative paths, and to output the resolved path prior to uploading, so the actual absolute path can be evaluated by the user.

### How can we reproduce it?

This is the GitHub Actions step I wrote:

```yaml
- name: Uploading artifacts
  uses: actions/upload-artifact@v4
  with:
    name: Build result
    path: $GITHUB_WORKSPACE/ProjectName/bin/Release/net9.0-windows/
    overwrite: true
    if-no-files-found: error
```

### What version of the action are you using?

@4

### What are your runner environments?

linux

**Comment by kdewald** [comment]
Seeing this same issue. Are there any workarounds?

**Comment by yacaovsnc** [comment]
You can use `${{ github.workspace }}` instead:

e.g.:
```
    - uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: ${{ github.workspace }}/artifact
```

**Comment by kdewald** [comment]
> You can use `${{ github.workspace }}` instead:
> 
> e.g.:
> 
> ```
>     - uses: actions/upload-artifact@v4
>       with:
>         name: artifact
>         path: ${{ github.workspace }}/artifact
> ```

It's not the same. Sometimes `${{ github.workspace }}` and `$GITHUB_WORKSPACE` don't match in all environments.

**Comment by tbertels** [comment]
What about this instead?
```
    - uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: ${{ env.GITHUB_WORKSPACE }}/artifact
```
