### ISSUE TITLE
Support tar.xz

### ISSUE THREAD

**Issue by xenoterracide** [actions/upload-artifact#69]
reason, improved compression, improved upload, improved download times. suggested structure is just to allow for expansiveness if needed

```yaml
     with:
         archive: tar
         compression: xz
```
recently testing the new glob feature, and having problems... I also tried doing it with tar.

 time to compress tar.xz and wrap in zip and upload 7s,  1.4MB
 time to compress zip and  upload 1m 15s,  21.5MB
