### ISSUE TITLE
[bug] name field doesn't support all-blob-reports-${{ matrix.shard }}

### ISSUE THREAD

**Issue by Poornachand200** [actions/upload-artifact#692]
### What happened?

 Error: The artifact name is not valid: all-blob-reports-1/5. Contains the following character:  Forward slash

```
Run actions/upload-artifact@v4
  with:
    name: all-blob-reports-1/5
    path: playwright/blob-report
    retention-days: 1
    if-no-files-found: warn
    compression-level: 6
    overwrite: false
    include-hidden-files: false
```

```
name: Playwright Tests
on:
  workflow_call:
    inputs:
      environment:
        description: "the environment to run automated tests against"
        required: true
        default: "warning"
        type: string

jobs:
  test:
    name: Automated tests
    strategy:
      fail-fast: false
      matrix:
        shard: [1/5, 2/5, 3/5, 4/5, 5/5]
    environment: ${{ inputs.environment }}
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache playwright
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwrightnode-${{ hashFiles('**/*package.json*') }}

      - name: Install dependencies
        run: npm ci
        working-directory: ./playwright

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./playwright

      - name: Run Playwright tests
        run: npx playwright test --shard ${{ matrix.shard }}
        working-directory: ./playwright
        env:
          PLAYWRIGHT_ENV: ${{ inputs.environment }}
          INCLUDE_MITID_TESTS: ${{ vars.INCLUDE_MITID_TESTS }}
          PLAYWRIGHT_SCIM_PROTECTION_PRIVATE_KEY: ${{secrets.PLAYWRIGHT_SCIM_PROTECTION_PRIVATE_KEY}}
          PLAYWRIGHT_SCIM_PROTECTION_JWK_KID: ${{secrets.PLAYWRIGHT_SCIM_PROTECTION_JWK_KID}}
          PLAYWRIGHT_SCIM_PROTECTION_CLIENT_NAME: ${{vars.PLAYWRIGHT_SCIM_PROTECTION_CLIENT_NAME}}
          PLAYWRIGHT_GOOGLE_WEAR_CLIENT_SECRET: ${{vars.PLAYWRIGHT_GOOGLE_WEAR_CLIENT_SECRET}}
          PLAYWRIGHT_ANDROID_YOUSEE_CLIENT_SECRET: ${{vars.PLAYWRIGHT_ANDROID_YOUSEE_CLIENT_SECRET}}
          PLAYWRIGHT_IOS_YOUSEE_CLIENT_SECRET: ${{vars.PLAYWRIGHT_IOS_YOUSEE_CLIENT_SECRET}}
          PLAYWRIGHT_SONOS_YOUSEE_CLIENT_SECRET: ${{vars.PLAYWRIGHT_SONOS_YOUSEE_CLIENT_SECRET}}
          PLAYWRIGHT_WEB_YOUSEE_CLIENT_SECRET: ${{vars.PLAYWRIGHT_WEB_YOUSEE_CLIENT_SECRET}}
          PLAYWRIGHT_SOUNDIIZ_CLIENT_NAME: ${{vars.PLAYWRIGHT_SOUNDIIZ_CLIENT_NAME}}
          PLAYWRIGHT_SOUNDIIZ_CLIENT_SECRET: ${{secrets.PLAYWRIGHT_SOUNDIIZ_CLIENT_SECRET}}
          PING_DIRECTORY_ADMIN_USER: ${{secrets.PING_DIRECTORY_ADMIN_USER}}
          PING_DIRECTORY_ADMIN_PASSWORD: ${{secrets.PING_DIRECTORY_ADMIN_PASSWORD}}
          PLAYWRIGHT_ANDROID_TV_CLIENT_SECRET: ${{secrets.PLAYWRIGHT_ANDROID_TV_CLIENT_SECRET}}
          PLAYWRIGHT_CLIENT_SECRET_NUUMUSICAPP_APPLE_WATCH_YOUSEE: ${{secrets.PLAYWRIGHT_CLIENT_SECRET_NUUMUSICAPP_APPLE_WATCH_YOUSEE}}
          BLOB_REPORTER: "true"

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: all-blob-reports-${{ matrix.shard }}
          path: playwright/blob-report
          retention-days: 1

```

### What did you expect to happen?

support / in name field

### How can we reproduce it?

Check the action workflow provided

### What version of the action are you using?

v4

### What are your runner environments?

self-hosted
