### ISSUE TITLE
[feat req] Add possibility to archive symbolic links properly

### ISSUE THREAD

**Issue by Panzerschrek** [actions/upload-artifact#693]
### What would you like to be added?

I use a script like this to upload my build artifacts:
```
    - uses: actions/upload-artifact@v4
      with:
        name: compiler_gnu_linux
        path: install/
```

Directory `install` contains several files and some symlinks for them in relative form. It's expected that symbolic links are archived as symbolic links in the result zip archive. But files are copied instead, and thus result archive becomes significantly larger in size.

### Why is this needed?

There should be an option to preserve symbolic links in result archive as is. Making this behavior default isn't optimal, since it may break some existing code which relies on old behavior.
