### ISSUE TITLE
Open source this action

### ISSUE THREAD

**Issue by eine** [actions/upload-artifact#7]
It is surprising that this repo (*the scripts and documentation in this project*) is licensed under MIT, since there is little to no relevant content to be licensed. However, I'm concerned about this from a practical point of view. I believe that most of the currently open issues (specially #3) could be fixed by the community, should we have any code to look at. It'd be really useful if the glue logic that gathers the artifacts and names them was open sourced, along with some minimal docs about the backend API that this action is using.

**Comment by matkoch** [comment]
I guess it's here: https://github.com/skx/github-action-publish-binaries

**Comment by tedmiston** [comment]
I also came looking for the source to see if `upload-artifact` supports me passing a command that returns a file path for the `path` input (e.g., `yarn cache dir`).

**Comment by madhurig** [comment]
We are working towards this, our goal is for the community to be able to contribute fixes.

**Comment by joshmgross** [comment]
@tedmiston You can use Action Outputs to do that, something like:
```yaml
- name: Get yarn cache
  id: yarn-cache
  run: echo "::set-output name=dir::$(yarn cache dir)"

- uses: actions/upload-artifact@v1
  with:
    path: ${{ steps.yarn-cache.outputs.dir }}
```
https://help.github.com/en/actions/automating-your-workflow-with-github-actions/metadata-syntax-for-github-actions#outputs

Though for that specific case, you probably want to use [`actions/cache`](https://github.com/actions/cache) instead
