### ISSUE TITLE
Line-ending/Whitespace changes 

### ISSUE THREAD

**Issue by aminya** [actions/upload-artifact#75]
When someone uses this script to upload and then download a file, line-ending changes, which generates a huge git noise.

I fixed this by running:
```
git diff -w --no-color || git apply --cached --ignore-whitespace && git checkout -- . && git reset && git add -p
```

But this should be fixed inside `upload-artifact`

**Comment by konradpabjan** [comment]
Thanks for opening this issue @aminya 

Do you have a minimal repo? (a `yaml` snippet would help immensely)

Does this effect a particular type of runner (Window, Linux, Mac)? I suspect (`CRLF` and `LF` shenanigans are going on behind the scenes.

**Comment by aminya** [comment]
Here you are. You can try different OS combinations:
```yaml
name: Test

on: push

defaults:
  run:
    shell: bash

jobs:
  Upload:
	runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload all
        uses: actions/upload-artifact@v2-preview
        with:
          path: ./

  Create_PR:
    needs: Upload
    runs-on: ubuntu-latest
    steps:
      - name: Download all
        uses: actions/download-artifact@v2
      - name: Move the content of the directory to the root
        run: |
          mv -v artifact/* ./
          mv -v artifact/.[^.]* ./
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: UploadTest
          title: "[AUTO] upload test"
          labels: UploadTest
          branch: "UploadTest"
```
