### ISSUE TITLE
Computed hash does not match with url signature

### ISSUE THREAD

**Issue by jy95** [actions/upload-artifact#77]
Hello,

Using actions/upload-artifact, I managed to upload a file using a customizable env variable : 
```yml
    env:
      FINAL_FILENAME: Source Code - un catalogue open source d’exercices informatiques.pdf
      LATEX_FILENAME: main.pdf
      MAIN_LATEX: main.tex
    steps:
       .....
      - name: rename ${{ env.LATEX_FILENAME }} to ${{ env.FINAL_FILENAME }}
        run: |
          mv "${{ env.LATEX_FILENAME }}" "${{ env.FINAL_FILENAME }}"
      - name: Upload result file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.FINAL_FILENAME }}
          path: ${{ env.FINAL_FILENAME }}
```
![bug42](https://user-images.githubusercontent.com/9306961/81431484-79d3cb80-9161-11ea-97b2-7693e18f6d51.PNG)

Which gives me the following url : 

[https://github.com/jy95/M-moire---Source-Code-un-catalogue-open-source-d-exercices-informatiques/suites/664591803/artifacts/5896280](https://github.com/jy95/M-moire---Source-Code-un-catalogue-open-source-d-exercices-informatiques/suites/664591803/artifacts/5896280)

When I request the url, I got this 
```json
{"count":47,"value":"Computed hash does not match with url signature"}
```

Any ideas ? The filename don't contain actions/toolkit [not supported characters](https://github.com/actions/toolkit/blob/master/packages/artifact/docs/additional-information.md#non-supported-characters)

PS : Please avoid answers like "use a filename without spaces" as I know the action works with regular filenames
