### ISSUE TITLE
[enhancement]: Upload files with their names

### ISSUE THREAD

**Issue by kittaakos** [actions/upload-artifact#80]
Inspired by [this](https://github.community/t5/GitHub-Actions/GitHub-Actions-Using-non-fixed-names-in-upload-artifact/m-p/58437/highlight/true#M10540).

I am not sure if this is possible at all as the artifacts are zipped, but I would like to upload files with their names. With Azure, it is possible to upload a directory and all artifacts will have their original file name.

Azure config:
```yaml
 - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: path/to/dir/with/artifacts/created/by/the/previous/task/
      artifactName: 'Arduino Pro IDE - Applications'
    displayName: Publish
```
Azure artifacts:
![Screen Shot 2020-05-15 at 09 22 29](https://user-images.githubusercontent.com/1405703/82044083-f9572280-96ac-11ea-992c-b1a579bde42f.jpg)

I have shamelessly copied your code 😊, modified it a bit, and set up another GH action that tries to demonstrate what I would consider a useful upload-feature. See here: https://github.com/kittaakos/upload-artifact-as-is

What do you think? Thanks for your time!
