### ISSUE TITLE
sanitize artifact names

### ISSUE THREAD

**Issue by aparcar** [actions/upload-artifact#83]
**Describe the bug**

I'm running a job matrix including with env variables like `foo/bar`. The artifact names should reflect those env variables, however the `name` may not contain special characters like a `/`. It would be convenient to replace non supported characters by `_`. 

**Version**
- [ ] V1
- [x] V2

**Environment*
- [ ] self-hosted
- [ ] Linux
- [ ] Windows
- [ ] Mac

**How to reproduce**

Try to create a artifact with the name `foo/bar`

**Comment by aparcar** [comment]
Ouhh this isn't really a bug but a feature. Can't remove the bug label sorry.

**Comment by aparcar** [comment]
![image](https://user-images.githubusercontent.com/16000931/82512884-1a54b480-9aad-11ea-8f4e-c6ad54a34bad.png)

**Comment by aparcar** [comment]
A solution is the following, however I'd prefer having this the default:

```yaml
    - name: sanitize target
      run: echo ::set-env name=TARGET_SANI::$(echo ${{ matrix.target }} | tr "/" "_")

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ env.TARGET_SANI }}
```
