### ISSUE TITLE
Clarify the meaning of "current working directory" in the readme

### ISSUE THREAD

**Issue by orthoxerox** [actions/upload-artifact#87]
**Describe the bug**
The readme says "Relative and absolute file paths are both allowed. Relative paths are rooted against the current working directory", but this doesn't mean the current working directory as reported by `pwd`, but the working directory of the job.

**Version**
- [?] V1
- [x] V2

**Environment**
- [ ] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

**Screenshots**

**Run/Repo Url**
[This run](https://github.com/orthoxerox/SDL2.Native/actions/runs/140230015) finishes with a warning because the file cannot be found, even though the previous step changed the working directory to the directory containing the artifact

[This run(absolute)](https://github.com/orthoxerox/SDL2.Native/actions/runs/140595194) and [this run (relative)](https://github.com/orthoxerox/SDL2.Native/actions/runs/140709693) finish correctly, because the relative path is relative to the starting directory of the job

**How to reproduce**
Add a `run` step before this step that changes the working directory via `cd`

**Comment by peterbraden** [comment]
It doesn't appear that it respects the default working directory?

https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#defaults

**Comment by ronlut** [comment]
> It doesn't appear that it respects the default working directory?
> 
> https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#defaults

Misleading indeed. I must say the workflow syntax documentation states it sets the working directory for **run** steps only, so maybe that's why it doesn't work as you would expect.

**Comment by andy-brainome** [comment]
Ran across the default working-directory issue myself.  
I expected it to just work but then again...

```
defaults:
  run:
    shell: bash
    working-directory: client

jobs:

  create_save_file:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: save file to disk
      run: |
        echo 'xyzzy' > save_file.txt

    - name: report file info
      run: |
        pwd
        ls -la save_file.txt
        echo "save_file.txt = `cat save_file.txt`"

    - name: save file for next job
      uses: actions/upload-artifact@v2
      with:
        name: save_file_txt
        path: client/save_file.txt
        if-no-files-found: error

    - name: save file for next job
      uses: actions/upload-artifact@v2
      with:
        name: save_file_txt
        path: save_file.txt
        if-no-files-found: error
```
