### ISSUE TITLE
Can not upload a directory that is a symlink to a directory

### ISSUE THREAD

**Issue by arianvp** [actions/upload-artifact#92]
**Describe the bug**
The [nix](https://nixos.org) package manager drops a symlink to the build artifact in your local directory called `result` which links
to the content-adressed build-directory e.g.:

```
lrwxrwxrwx 1 arian users 50 Jul  6 15:10 result -> /nix/store/qk0wg6wv073bz78llr582by4x3n59kgk-jekyll
```
but uploading that directory fails using the following workflow:
```yaml
    - name: "Build"
      run: nix-build -A website
    - name: "Upload artifact to github"
      uses: actions/upload-artifact@v2
      with:
        name: website
        path: result/**/*
```

However as a workaround, if you create a directory _inside_ that symlink then it does work:

```yaml
    - name: "Build"
      run: nix-build -A website
    - name: "Upload artifact to github"
      uses: actions/upload-artifact@v2
      with:
        name: website
        path: result/dummy-directory/**/*
```

**Version**
- [ ] V1
- [x] V2

**Environment**
- [ ] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

**Screenshots**

**Run/Repo Url**
https://github.com/minvws/nl-covid19-notification-app-community-website/runs/841910187?check_suite_focus=true

**How to reproduce**
If applicable, add information on how to reproduce the problem.

**Additional context**

**Comment by arianvp** [comment]
Funnily enough; the code does detect that it's a directory, and even tells me how many files will be uploaded; to only later fail:

```
With the provided path, there will be 11 files uploaded
##[error]Provided rootDirectory /home/runner/work/nl-covid19-notification-app-community-website/nl-covid19-notification-app-community-website/result is not a valid directory
```

The fix seems like we should first resolve symlinks before checking with `lstat` whether the file is a directory

**Comment by rpearce** [comment]
Same issue here: https://github.com/rpearce/robertwpearce.com/pull/68/checks?check_run_id=1109884668

@arianvp Is the workaround to have a directory inside the symlinked dir?

**Comment by grigorye** [comment]
Just in case, another workaround (that works in my case) might be using glob pattern instead of the exact name for the directory. Given the orginal example, something like this:

```
    - name: "Upload artifact to github"
      uses: actions/upload-artifact@v2
      with:
        name: website
        path: result*/**/*
```

In case the glob does match extra (irrelevant) directories, I wonder if you could use `!` to filter out non-related stuff e.g. like below:
```
    - name: "Upload artifact to github"
      uses: actions/upload-artifact@v2
      with:
        name: website
        path:
        - result*/**/*
        - !result?*
```

**Comment by gebn** [comment]
I'm also running into this with Bazel, which symlinks `bazel-bin` in the workspace directory:

```yaml
- uses: actions/upload-artifact@v2
  with:
    name: archive
    path: bazel-bin/archive.tar.gz
```
```
Run actions/upload-artifact@v2
With the provided path, there will be 1 file(s) uploaded
Error: Provided rootDirectory /home/runner/work/slug/slug/bazel-bin is not a valid directory
```

Bazel provides `bazel info bazel-bin` to get the real path, however it looks like command substitution isn't supported within `path`.

**Comment by SCOTT-HAMILTON** [comment]
I can reproduce this same exact issue with a nix result folder symlink.

```yaml
    - name: "Upload artifact to github"
      uses: actions/upload-artifact@v2
      with:
        name: Test-driver screenshots
        path: result/screen*
```

**Comment by RachelXGanon** [comment]
Is this bug fixed?
I'm using a symbolic link in windows, with this action and get 
`Error: Provided rootDirectory<path> is not a valid directory
`

**Comment by zhangguanzhang** [comment]
Is this bug fixed?
I'm using a symbolic link in windows, with this action and get
```
Error: Provided rootDirectory /home/runner/work/Actions-OpenWrt/Actions-OpenWrt/openwrt is not a valid directory
```

**Comment by finolacahill** [comment]
+1 on this issue. Failing out for a symlinked directory

**Comment by n8henrie** [comment]
Running into this error (`Error: Provided rootDirectory /tmp is not a valid directory`) on a macos builder, trying to upload `/tmp/qs_build_settings`.

https://github.com/quicksilver/Quicksilver/runs/5321405744?check_suite_focus=true

```
Run actions/upload-artifact@v2
  with:
    name: BUILD_SETTINGS
    path: /tmp/qs_build_settings
    if-no-files-found: warn
  env:
    QS_BUILD_ONLY: 1
With the provided path, there will be 1 file uploaded
Starting artifact upload
For more detailed logs during the artifact upload process, enable step-debugging: https://docs.github.com/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging
Artifact name is valid!
Error: Provided rootDirectory /tmp is not a valid directory
```

Trying to debug:

```
+ ls -l /tmp/qs_build_settings
-rw-r--r--  1 runner  wheel  27668 Feb 24 16:02 /tmp/qs_build_settings
+ ls -ldh /tmp
lrwxr-xr-x@ 1 root  wheel    11B Jan  1  2020 /tmp -> private/tmp
```

**Comment by exFalso** [comment]
Note, workaround is to dereference the symlink with `readlink` and pass it through with `$GITHUB_ENV`:

```yaml
      - run: nix-build XXX # produces `result` symlink
      - run: echo "UPLOAD_PATH=$(readlink -f result)" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v2
        with:
          name: XXX
          path: ${{ env.UPLOAD_PATH }}
```
